package com.youlema.sales.mapper;

import com.youlema.sales.mapper.meta.AgentsAccountAdmin;
import com.youlema.sales.mapper.meta.AgentsAccountAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
/**
 * 代理商管理员Mapper
 * @author zhushijun
 *
 */
public interface AgentsAccountAdminMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Account_Admin
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int countByExample(AgentsAccountAdminExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Account_Admin
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int deleteByExample(AgentsAccountAdminExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Account_Admin
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int deleteByPrimaryKey(Long agentsAccountId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Account_Admin
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int insert(AgentsAccountAdmin record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Account_Admin
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int insertSelective(AgentsAccountAdmin record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Account_Admin
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    List<AgentsAccountAdmin> selectByExample(AgentsAccountAdminExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Account_Admin
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    AgentsAccountAdmin selectByPrimaryKey(Long agentsAccountId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Account_Admin
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int updateByExampleSelective(@Param("record") AgentsAccountAdmin record,
            @Param("example") AgentsAccountAdminExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Account_Admin
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int updateByExample(@Param("record") AgentsAccountAdmin record, @Param("example") AgentsAccountAdminExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Account_Admin
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int updateByPrimaryKeySelective(AgentsAccountAdmin record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Account_Admin
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int updateByPrimaryKey(AgentsAccountAdmin record);

}
