package com.youlema.sales.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.youlema.sales.mapper.meta.AgentsMenu;
import com.youlema.sales.mapper.meta.AgentsMenuExample;
/**
 * 代理商菜单Mapper
 * @author zhushijun
 *
 */
public interface AgentsMenuMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Menu
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int countByExample(AgentsMenuExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Menu
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int deleteByExample(AgentsMenuExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Menu
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int deleteByPrimaryKey(Long agentsMenuId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Menu
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int insert(AgentsMenu record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Menu
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int insertSelective(AgentsMenu record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Menu
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    List<AgentsMenu> selectByExample(AgentsMenuExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Menu
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    AgentsMenu selectByPrimaryKey(Long agentsMenuId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Menu
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int updateByExampleSelective(@Param("record") AgentsMenu record, @Param("example") AgentsMenuExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Menu
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int updateByExample(@Param("record") AgentsMenu record, @Param("example") AgentsMenuExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Menu
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int updateByPrimaryKeySelective(AgentsMenu record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Menu
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int updateByPrimaryKey(AgentsMenu record);

}
