package com.youlema.sales.mapper;

import com.youlema.sales.mapper.meta.AgentsFavorites;
import com.youlema.sales.mapper.meta.AgentsFavoritesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
/**
 * 代理商收藏表Mapper
 * @author zhushijun
 *
 */
public interface AgentsFavoritesMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Favorites
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int countByExample(AgentsFavoritesExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Favorites
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int deleteByExample(AgentsFavoritesExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Favorites
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int deleteByPrimaryKey(Long agentsFavoritesId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Favorites
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int insert(AgentsFavorites record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Favorites
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int insertSelective(AgentsFavorites record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Favorites
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    List<AgentsFavorites> selectByExample(AgentsFavoritesExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Favorites
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    AgentsFavorites selectByPrimaryKey(Long agentsFavoritesId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Favorites
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int updateByExampleSelective(@Param("record") AgentsFavorites record,
            @Param("example") AgentsFavoritesExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Favorites
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int updateByExample(@Param("record") AgentsFavorites record, @Param("example") AgentsFavoritesExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Favorites
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int updateByPrimaryKeySelective(AgentsFavorites record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table Agents_Favorites
     * @mbggenerated  Mon Jun 17 23:46:53 CST 2013
     */
    int updateByPrimaryKey(AgentsFavorites record);

}
