package com.youlema.sales.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.youlema.sales.mapper.meta.AgentsTotalFact;
import com.youlema.sales.mapper.meta.AgentsTotalFactExample;

public interface AgentsTotalFactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTS_TOTAL_FACT
     *
     * @mbggenerated Sun Aug 25 22:14:35 CST 2013
     */
    int countByExample(AgentsTotalFactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTS_TOTAL_FACT
     *
     * @mbggenerated Sun Aug 25 22:14:35 CST 2013
     */
    int deleteByExample(AgentsTotalFactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTS_TOTAL_FACT
     *
     * @mbggenerated Sun Aug 25 22:14:35 CST 2013
     */
    int deleteByPrimaryKey(Long agentsTotalFactId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTS_TOTAL_FACT
     *
     * @mbggenerated Sun Aug 25 22:14:35 CST 2013
     */
    int insert(AgentsTotalFact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTS_TOTAL_FACT
     *
     * @mbggenerated Sun Aug 25 22:14:35 CST 2013
     */
    int insertSelective(AgentsTotalFact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTS_TOTAL_FACT
     *
     * @mbggenerated Sun Aug 25 22:14:35 CST 2013
     */
    List<AgentsTotalFact> selectByExample(AgentsTotalFactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTS_TOTAL_FACT
     *
     * @mbggenerated Sun Aug 25 22:14:35 CST 2013
     */
    AgentsTotalFact selectByPrimaryKey(Long agentsTotalFactId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTS_TOTAL_FACT
     *
     * @mbggenerated Sun Aug 25 22:14:35 CST 2013
     */
    int updateByExampleSelective(@Param("record") AgentsTotalFact record, @Param("example") AgentsTotalFactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTS_TOTAL_FACT
     *
     * @mbggenerated Sun Aug 25 22:14:35 CST 2013
     */
    int updateByExample(@Param("record") AgentsTotalFact record, @Param("example") AgentsTotalFactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTS_TOTAL_FACT
     *
     * @mbggenerated Sun Aug 25 22:14:35 CST 2013
     */
    int updateByPrimaryKeySelective(AgentsTotalFact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AGENTS_TOTAL_FACT
     *
     * @mbggenerated Sun Aug 25 22:14:35 CST 2013
     */
    int updateByPrimaryKey(AgentsTotalFact record);
}