package com.youlema.sales.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.youlema.sales.mapper.meta.AgentsAccount;
import com.youlema.sales.mapper.meta.AgentsAccountExample;
/**
 * 代理商账号表Mapper
 * @author zhushijun
 *
 */
public interface AgentsAccountMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_ACCOUNT
     * @mbggenerated  Fri Aug 09 16:24:30 CST 2013
     */
    int countByExample(AgentsAccountExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_ACCOUNT
     * @mbggenerated  Fri Aug 09 16:24:30 CST 2013
     */
    int deleteByExample(AgentsAccountExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_ACCOUNT
     * @mbggenerated  Fri Aug 09 16:24:30 CST 2013
     */
    int deleteByPrimaryKey(Long agentsAccountId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_ACCOUNT
     * @mbggenerated  Fri Aug 09 16:24:30 CST 2013
     */
    int insert(AgentsAccount record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_ACCOUNT
     * @mbggenerated  Fri Aug 09 16:24:30 CST 2013
     */
    int insertSelective(AgentsAccount record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_ACCOUNT
     * @mbggenerated  Fri Aug 09 16:24:30 CST 2013
     */
    List<AgentsAccount> selectByExample(AgentsAccountExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_ACCOUNT
     * @mbggenerated  Fri Aug 09 16:24:30 CST 2013
     */
    AgentsAccount selectByPrimaryKey(Long agentsAccountId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_ACCOUNT
     * @mbggenerated  Fri Aug 09 16:24:30 CST 2013
     */
    int updateByExampleSelective(@Param("record") AgentsAccount record, @Param("example") AgentsAccountExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_ACCOUNT
     * @mbggenerated  Fri Aug 09 16:24:30 CST 2013
     */
    int updateByExample(@Param("record") AgentsAccount record, @Param("example") AgentsAccountExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_ACCOUNT
     * @mbggenerated  Fri Aug 09 16:24:30 CST 2013
     */
    int updateByPrimaryKeySelective(AgentsAccount record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_ACCOUNT
     * @mbggenerated  Fri Aug 09 16:24:30 CST 2013
     */
    int updateByPrimaryKey(AgentsAccount record);

}
