package com.youlema.sales.mapper;

import com.youlema.sales.mapper.meta.AssAgentsAccountRoleExample;
import com.youlema.sales.mapper.meta.AssAgentsAccountRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssAgentsAccountRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASS_AGENTS_ACCOUNT_ROLE
     *
     * @mbggenerated Thu Aug 22 20:47:00 CST 2013
     */
    int countByExample(AssAgentsAccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASS_AGENTS_ACCOUNT_ROLE
     *
     * @mbggenerated Thu Aug 22 20:47:00 CST 2013
     */
    int deleteByExample(AssAgentsAccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASS_AGENTS_ACCOUNT_ROLE
     *
     * @mbggenerated Thu Aug 22 20:47:00 CST 2013
     */
    int deleteByPrimaryKey(AssAgentsAccountRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASS_AGENTS_ACCOUNT_ROLE
     *
     * @mbggenerated Thu Aug 22 20:47:00 CST 2013
     */
    int insert(AssAgentsAccountRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASS_AGENTS_ACCOUNT_ROLE
     *
     * @mbggenerated Thu Aug 22 20:47:00 CST 2013
     */
    int insertSelective(AssAgentsAccountRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASS_AGENTS_ACCOUNT_ROLE
     *
     * @mbggenerated Thu Aug 22 20:47:00 CST 2013
     */
    List<AssAgentsAccountRoleKey> selectByExample(AssAgentsAccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASS_AGENTS_ACCOUNT_ROLE
     *
     * @mbggenerated Thu Aug 22 20:47:00 CST 2013
     */
    int updateByExampleSelective(@Param("record") AssAgentsAccountRoleKey record, @Param("example") AssAgentsAccountRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASS_AGENTS_ACCOUNT_ROLE
     *
     * @mbggenerated Thu Aug 22 20:47:00 CST 2013
     */
    int updateByExample(@Param("record") AssAgentsAccountRoleKey record, @Param("example") AssAgentsAccountRoleExample example);
}