package com.youlema.sales.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.youlema.sales.mapper.meta.ProductType;
import com.youlema.sales.mapper.meta.ProductTypeExample;

public interface ProductTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_TYPE
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    int countByExample(ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_TYPE
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    int deleteByExample(ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_TYPE
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    int deleteByPrimaryKey(Long productTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_TYPE
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    int insert(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_TYPE
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    int insertSelective(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_TYPE
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    List<ProductType> selectByExample(ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_TYPE
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    ProductType selectByPrimaryKey(Long productTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_TYPE
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    int updateByExampleSelective(@Param("record") ProductType record, @Param("example") ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_TYPE
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    int updateByExample(@Param("record") ProductType record, @Param("example") ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_TYPE
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    int updateByPrimaryKeySelective(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_TYPE
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    int updateByPrimaryKey(ProductType record);
}