package com.youlema.sales.mapper.meta;

import java.util.Date;

public class AgentsRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_ID
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    private Long agentsPrivilegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS_PRIVILEGE.PARENT_ID
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_NAME
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    private String agentsPrivilegeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_CODE
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    private String agentsPrivilegeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_TYPE
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    private String agentsPrivilegeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_MEMO
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    private String agentsPrivilegeMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS_PRIVILEGE.CREATOR
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS_PRIVILEGE.GMT_CREATE
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS_PRIVILEGE.MODIFIER
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS_PRIVILEGE.GMT_MODIFY
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    private Date gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS_PRIVILEGE.IS_ENABLE
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    private Boolean isEnable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_ID
     *
     * @return the value of AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_ID
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    public Long getAgentsPrivilegeId() {
        return agentsPrivilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_ID
     *
     * @param agentsPrivilegeId the value for AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_ID
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    public void setAgentsPrivilegeId(Long agentsPrivilegeId) {
        this.agentsPrivilegeId = agentsPrivilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS_PRIVILEGE.PARENT_ID
     *
     * @return the value of AGENTS_PRIVILEGE.PARENT_ID
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS_PRIVILEGE.PARENT_ID
     *
     * @param parentId the value for AGENTS_PRIVILEGE.PARENT_ID
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_NAME
     *
     * @return the value of AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_NAME
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    public String getAgentsPrivilegeName() {
        return agentsPrivilegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_NAME
     *
     * @param agentsPrivilegeName the value for AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_NAME
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    public void setAgentsPrivilegeName(String agentsPrivilegeName) {
        this.agentsPrivilegeName = agentsPrivilegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_CODE
     *
     * @return the value of AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_CODE
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    public String getAgentsPrivilegeCode() {
        return agentsPrivilegeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_CODE
     *
     * @param agentsPrivilegeCode the value for AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_CODE
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    public void setAgentsPrivilegeCode(String agentsPrivilegeCode) {
        this.agentsPrivilegeCode = agentsPrivilegeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_TYPE
     *
     * @return the value of AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_TYPE
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    public String getAgentsPrivilegeType() {
        return agentsPrivilegeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_TYPE
     *
     * @param agentsPrivilegeType the value for AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_TYPE
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    public void setAgentsPrivilegeType(String agentsPrivilegeType) {
        this.agentsPrivilegeType = agentsPrivilegeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_MEMO
     *
     * @return the value of AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_MEMO
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    public String getAgentsPrivilegeMemo() {
        return agentsPrivilegeMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_MEMO
     *
     * @param agentsPrivilegeMemo the value for AGENTS_PRIVILEGE.AGENTS_PRIVILEGE_MEMO
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    public void setAgentsPrivilegeMemo(String agentsPrivilegeMemo) {
        this.agentsPrivilegeMemo = agentsPrivilegeMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS_PRIVILEGE.CREATOR
     *
     * @return the value of AGENTS_PRIVILEGE.CREATOR
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS_PRIVILEGE.CREATOR
     *
     * @param creator the value for AGENTS_PRIVILEGE.CREATOR
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS_PRIVILEGE.GMT_CREATE
     *
     * @return the value of AGENTS_PRIVILEGE.GMT_CREATE
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS_PRIVILEGE.GMT_CREATE
     *
     * @param gmtCreate the value for AGENTS_PRIVILEGE.GMT_CREATE
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS_PRIVILEGE.MODIFIER
     *
     * @return the value of AGENTS_PRIVILEGE.MODIFIER
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS_PRIVILEGE.MODIFIER
     *
     * @param modifier the value for AGENTS_PRIVILEGE.MODIFIER
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS_PRIVILEGE.GMT_MODIFY
     *
     * @return the value of AGENTS_PRIVILEGE.GMT_MODIFY
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS_PRIVILEGE.GMT_MODIFY
     *
     * @param gmtModify the value for AGENTS_PRIVILEGE.GMT_MODIFY
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS_PRIVILEGE.IS_ENABLE
     *
     * @return the value of AGENTS_PRIVILEGE.IS_ENABLE
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS_PRIVILEGE.IS_ENABLE
     *
     * @param isEnable the value for AGENTS_PRIVILEGE.IS_ENABLE
     *
     * @mbggenerated Thu Aug 22 21:14:36 CST 2013
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }
}