package com.youlema.sales.mapper.meta;

import java.util.Date;

import com.youlema.sales.meta.BusinessType;

public class AgentsFavorites {

    private TourLine tourLine;

    public TourLine getTourLine() {
        return tourLine;
    }

    public void setTourLine(TourLine tourLine) {
        this.tourLine = tourLine;
    }

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column Agents_Favorites.agents_Favorites_Id
     * 
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    private Long agentsFavoritesId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column Agents_Favorites.agents_Account_Id
     * 
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    private Long agentsAccountId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column Agents_Favorites.gmt_Of_Favorites
     * 
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    private Date gmtOfFavorites;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column Agents_Favorites.memo
     * 
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column Agents_Favorites.business_Id
     * 
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    private Long businessId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column Agents_Favorites.business_Type
     * 
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    private String businessType;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column Agents_Favorites.agents_Favorites_Id
     * 
     * @return the value of Agents_Favorites.agents_Favorites_Id
     * 
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public Long getAgentsFavoritesId() {
        return agentsFavoritesId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column Agents_Favorites.agents_Favorites_Id
     * 
     * @param agentsFavoritesId
     *            the value for Agents_Favorites.agents_Favorites_Id
     * 
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public void setAgentsFavoritesId(Long agentsFavoritesId) {
        this.agentsFavoritesId = agentsFavoritesId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column Agents_Favorites.agents_Account_Id
     * 
     * @return the value of Agents_Favorites.agents_Account_Id
     * 
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public Long getAgentsAccountId() {
        return agentsAccountId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column Agents_Favorites.agents_Account_Id
     * 
     * @param agentsAccountId
     *            the value for Agents_Favorites.agents_Account_Id
     * 
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public void setAgentsAccountId(Long agentsAccountId) {
        this.agentsAccountId = agentsAccountId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column Agents_Favorites.gmt_Of_Favorites
     * 
     * @return the value of Agents_Favorites.gmt_Of_Favorites
     * 
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public Date getGmtOfFavorites() {
        return gmtOfFavorites;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column Agents_Favorites.gmt_Of_Favorites
     * 
     * @param gmtOfFavorites
     *            the value for Agents_Favorites.gmt_Of_Favorites
     * 
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public void setGmtOfFavorites(Date gmtOfFavorites) {
        this.gmtOfFavorites = gmtOfFavorites;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column Agents_Favorites.memo
     * 
     * @return the value of Agents_Favorites.memo
     * 
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column Agents_Favorites.memo
     * 
     * @param memo
     *            the value for Agents_Favorites.memo
     * 
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column Agents_Favorites.business_Id
     * 
     * @return the value of Agents_Favorites.business_Id
     * 
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column Agents_Favorites.business_Id
     * 
     * @param businessId
     *            the value for Agents_Favorites.business_Id
     * 
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column Agents_Favorites.business_Type
     * 
     * @return the value of Agents_Favorites.business_Type
     * 
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column Agents_Favorites.business_Type
     * 
     * @param businessType
     *            the value for Agents_Favorites.business_Type
     * 
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }

    public BusinessType getBusinessTypeObject() {
        return BusinessType.valueOf(businessType);
    }

}