package com.youlema.sales.mapper.meta;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AgentsFavoritesExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table AGENTS_FAVORITES
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table AGENTS_FAVORITES
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table AGENTS_FAVORITES
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_FAVORITES
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    public AgentsFavoritesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_FAVORITES
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_FAVORITES
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_FAVORITES
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_FAVORITES
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_FAVORITES
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_FAVORITES
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_FAVORITES
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_FAVORITES
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_FAVORITES
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_FAVORITES
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table AGENTS_FAVORITES
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAgentsFavoritesIdIsNull() {
            addCriterion("AGENTS_FAVORITES_ID is null");
            return (Criteria) this;
        }

        public Criteria andAgentsFavoritesIdIsNotNull() {
            addCriterion("AGENTS_FAVORITES_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAgentsFavoritesIdEqualTo(Long value) {
            addCriterion("AGENTS_FAVORITES_ID =", value, "agentsFavoritesId");
            return (Criteria) this;
        }

        public Criteria andAgentsFavoritesIdNotEqualTo(Long value) {
            addCriterion("AGENTS_FAVORITES_ID <>", value, "agentsFavoritesId");
            return (Criteria) this;
        }

        public Criteria andAgentsFavoritesIdGreaterThan(Long value) {
            addCriterion("AGENTS_FAVORITES_ID >", value, "agentsFavoritesId");
            return (Criteria) this;
        }

        public Criteria andAgentsFavoritesIdGreaterThanOrEqualTo(Long value) {
            addCriterion("AGENTS_FAVORITES_ID >=", value, "agentsFavoritesId");
            return (Criteria) this;
        }

        public Criteria andAgentsFavoritesIdLessThan(Long value) {
            addCriterion("AGENTS_FAVORITES_ID <", value, "agentsFavoritesId");
            return (Criteria) this;
        }

        public Criteria andAgentsFavoritesIdLessThanOrEqualTo(Long value) {
            addCriterion("AGENTS_FAVORITES_ID <=", value, "agentsFavoritesId");
            return (Criteria) this;
        }

        public Criteria andAgentsFavoritesIdIn(List<Long> values) {
            addCriterion("AGENTS_FAVORITES_ID in", values, "agentsFavoritesId");
            return (Criteria) this;
        }

        public Criteria andAgentsFavoritesIdNotIn(List<Long> values) {
            addCriterion("AGENTS_FAVORITES_ID not in", values, "agentsFavoritesId");
            return (Criteria) this;
        }

        public Criteria andAgentsFavoritesIdBetween(Long value1, Long value2) {
            addCriterion("AGENTS_FAVORITES_ID between", value1, value2, "agentsFavoritesId");
            return (Criteria) this;
        }

        public Criteria andAgentsFavoritesIdNotBetween(Long value1, Long value2) {
            addCriterion("AGENTS_FAVORITES_ID not between", value1, value2, "agentsFavoritesId");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdIsNull() {
            addCriterion("AGENTS_ACCOUNT_ID is null");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdIsNotNull() {
            addCriterion("AGENTS_ACCOUNT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdEqualTo(Long value) {
            addCriterion("AGENTS_ACCOUNT_ID =", value, "agentsAccountId");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdNotEqualTo(Long value) {
            addCriterion("AGENTS_ACCOUNT_ID <>", value, "agentsAccountId");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdGreaterThan(Long value) {
            addCriterion("AGENTS_ACCOUNT_ID >", value, "agentsAccountId");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdGreaterThanOrEqualTo(Long value) {
            addCriterion("AGENTS_ACCOUNT_ID >=", value, "agentsAccountId");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdLessThan(Long value) {
            addCriterion("AGENTS_ACCOUNT_ID <", value, "agentsAccountId");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdLessThanOrEqualTo(Long value) {
            addCriterion("AGENTS_ACCOUNT_ID <=", value, "agentsAccountId");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdIn(List<Long> values) {
            addCriterion("AGENTS_ACCOUNT_ID in", values, "agentsAccountId");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdNotIn(List<Long> values) {
            addCriterion("AGENTS_ACCOUNT_ID not in", values, "agentsAccountId");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdBetween(Long value1, Long value2) {
            addCriterion("AGENTS_ACCOUNT_ID between", value1, value2, "agentsAccountId");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdNotBetween(Long value1, Long value2) {
            addCriterion("AGENTS_ACCOUNT_ID not between", value1, value2, "agentsAccountId");
            return (Criteria) this;
        }

        public Criteria andGmtOfFavoritesIsNull() {
            addCriterion("GMT_OF_FAVORITES is null");
            return (Criteria) this;
        }

        public Criteria andGmtOfFavoritesIsNotNull() {
            addCriterion("GMT_OF_FAVORITES is not null");
            return (Criteria) this;
        }

        public Criteria andGmtOfFavoritesEqualTo(Date value) {
            addCriterion("GMT_OF_FAVORITES =", value, "gmtOfFavorites");
            return (Criteria) this;
        }

        public Criteria andGmtOfFavoritesNotEqualTo(Date value) {
            addCriterion("GMT_OF_FAVORITES <>", value, "gmtOfFavorites");
            return (Criteria) this;
        }

        public Criteria andGmtOfFavoritesGreaterThan(Date value) {
            addCriterion("GMT_OF_FAVORITES >", value, "gmtOfFavorites");
            return (Criteria) this;
        }

        public Criteria andGmtOfFavoritesGreaterThanOrEqualTo(Date value) {
            addCriterion("GMT_OF_FAVORITES >=", value, "gmtOfFavorites");
            return (Criteria) this;
        }

        public Criteria andGmtOfFavoritesLessThan(Date value) {
            addCriterion("GMT_OF_FAVORITES <", value, "gmtOfFavorites");
            return (Criteria) this;
        }

        public Criteria andGmtOfFavoritesLessThanOrEqualTo(Date value) {
            addCriterion("GMT_OF_FAVORITES <=", value, "gmtOfFavorites");
            return (Criteria) this;
        }

        public Criteria andGmtOfFavoritesIn(List<Date> values) {
            addCriterion("GMT_OF_FAVORITES in", values, "gmtOfFavorites");
            return (Criteria) this;
        }

        public Criteria andGmtOfFavoritesNotIn(List<Date> values) {
            addCriterion("GMT_OF_FAVORITES not in", values, "gmtOfFavorites");
            return (Criteria) this;
        }

        public Criteria andGmtOfFavoritesBetween(Date value1, Date value2) {
            addCriterion("GMT_OF_FAVORITES between", value1, value2, "gmtOfFavorites");
            return (Criteria) this;
        }

        public Criteria andGmtOfFavoritesNotBetween(Date value1, Date value2) {
            addCriterion("GMT_OF_FAVORITES not between", value1, value2, "gmtOfFavorites");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("MEMO is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("MEMO is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("MEMO =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("MEMO <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("MEMO >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("MEMO >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("MEMO <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("MEMO <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("MEMO like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("MEMO not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("MEMO in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("MEMO not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("MEMO between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("MEMO not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andBusinessIdIsNull() {
            addCriterion("BUSINESS_ID is null");
            return (Criteria) this;
        }

        public Criteria andBusinessIdIsNotNull() {
            addCriterion("BUSINESS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessIdEqualTo(Long value) {
            addCriterion("BUSINESS_ID =", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdNotEqualTo(Long value) {
            addCriterion("BUSINESS_ID <>", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdGreaterThan(Long value) {
            addCriterion("BUSINESS_ID >", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdGreaterThanOrEqualTo(Long value) {
            addCriterion("BUSINESS_ID >=", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdLessThan(Long value) {
            addCriterion("BUSINESS_ID <", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdLessThanOrEqualTo(Long value) {
            addCriterion("BUSINESS_ID <=", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdIn(List<Long> values) {
            addCriterion("BUSINESS_ID in", values, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdNotIn(List<Long> values) {
            addCriterion("BUSINESS_ID not in", values, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdBetween(Long value1, Long value2) {
            addCriterion("BUSINESS_ID between", value1, value2, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdNotBetween(Long value1, Long value2) {
            addCriterion("BUSINESS_ID not between", value1, value2, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeIsNull() {
            addCriterion("BUSINESS_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeIsNotNull() {
            addCriterion("BUSINESS_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeEqualTo(String value) {
            addCriterion("BUSINESS_TYPE =", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotEqualTo(String value) {
            addCriterion("BUSINESS_TYPE <>", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeGreaterThan(String value) {
            addCriterion("BUSINESS_TYPE >", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINESS_TYPE >=", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeLessThan(String value) {
            addCriterion("BUSINESS_TYPE <", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeLessThanOrEqualTo(String value) {
            addCriterion("BUSINESS_TYPE <=", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeLike(String value) {
            addCriterion("BUSINESS_TYPE like", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotLike(String value) {
            addCriterion("BUSINESS_TYPE not like", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeIn(List<String> values) {
            addCriterion("BUSINESS_TYPE in", values, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotIn(List<String> values) {
            addCriterion("BUSINESS_TYPE not in", values, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeBetween(String value1, String value2) {
            addCriterion("BUSINESS_TYPE between", value1, value2, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotBetween(String value1, String value2) {
            addCriterion("BUSINESS_TYPE not between", value1, value2, "businessType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table AGENTS_FAVORITES
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    public static class Criterion {
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Agents_Favorites
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 17 23:46:53 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}