package com.youlema.sales.mapper.meta;

import java.io.Serializable;
import java.util.Date;

public class Agents implements Serializable{
    /**
     * 
     */
    private static final long serialVersionUID = -6521512333357473768L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.AGENTS_ID
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private Long agentsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.AGENTS_NAME
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String agentsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.AGENTS_TYPE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String agentsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.AGENTS_CODE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String agentsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.AREA
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.AGENTS_TEL
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String agentsTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.AGENTS_FAX
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String agentsFax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.AGENTS_MAIL
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String agentsMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.AGENTS_SITE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String agentsSite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.AGENTS_ADDR
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String agentsAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.ZIP_CODE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.IS_ENABLE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private Boolean isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.AGENTS_LEVEL
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String agentsLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.OPERATING_RANGE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String operatingRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.AGENT_APPLICATION_ID
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private Long agentApplicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.LICENSE_NO
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String licenseNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.TYPE_OF_CONTRACT
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String typeOfContract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.IS_SHOW_PRICES
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String isShowPrices;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.AGENTS_STATUS
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String agentsStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.ACCOUNT_EXECUTIVE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String accountExecutive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.AGENTS_CONTACT
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String agentsContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.CONTACT_PHONE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String contactPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.AGENTS_INTRODUCTION
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String agentsIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.BASIC_INFO_AUDIT_STATUS
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String basicInfoAuditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.BASIC_INFO_AUDITOR
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String basicInfoAuditor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.GMT_BASIC_INFO_AUDIT
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private Date gmtBasicInfoAudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.BASIC_INFO_AUDIT_OPINION
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String basicInfoAuditOpinion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.FINANCAIL_INFO_AUDIT_STATUS
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String financailInfoAuditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.FINANCAIL_INFO_AUDITOR
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String financailInfoAuditor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.GMT_FINANCAIL_INFO_AUDIT
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private Date gmtFinancailInfoAudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.FINANCAIL_INFO_AUDIT_OPINION
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String financailInfoAuditOpinion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.CREATOR
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.GMT_CREATE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.MODIFIER
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.GMT_MODIFY
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private Date gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.IS_EDIT
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private Boolean isEdit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.IS_CREDIT
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private Boolean isCredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.IS_LIMIT_BOOKING
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private Boolean isLimitBooking;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.LEGAL_REPRESENTATIVE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String legalRepresentative;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.AGENTS_SIMPLE_NAME
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private String agentsSimpleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AGENTS.IS_PRINT
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    private Boolean isPrint;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.AGENTS_ID
     *
     * @return the value of AGENTS.AGENTS_ID
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public Long getAgentsId() {
        return agentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.AGENTS_ID
     *
     * @param agentsId the value for AGENTS.AGENTS_ID
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setAgentsId(Long agentsId) {
        this.agentsId = agentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.AGENTS_NAME
     *
     * @return the value of AGENTS.AGENTS_NAME
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getAgentsName() {
        return agentsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.AGENTS_NAME
     *
     * @param agentsName the value for AGENTS.AGENTS_NAME
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setAgentsName(String agentsName) {
        this.agentsName = agentsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.AGENTS_TYPE
     *
     * @return the value of AGENTS.AGENTS_TYPE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getAgentsType() {
        return agentsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.AGENTS_TYPE
     *
     * @param agentsType the value for AGENTS.AGENTS_TYPE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setAgentsType(String agentsType) {
        this.agentsType = agentsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.AGENTS_CODE
     *
     * @return the value of AGENTS.AGENTS_CODE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getAgentsCode() {
        return agentsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.AGENTS_CODE
     *
     * @param agentsCode the value for AGENTS.AGENTS_CODE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setAgentsCode(String agentsCode) {
        this.agentsCode = agentsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.AREA
     *
     * @return the value of AGENTS.AREA
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.AREA
     *
     * @param area the value for AGENTS.AREA
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.AGENTS_TEL
     *
     * @return the value of AGENTS.AGENTS_TEL
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getAgentsTel() {
        return agentsTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.AGENTS_TEL
     *
     * @param agentsTel the value for AGENTS.AGENTS_TEL
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setAgentsTel(String agentsTel) {
        this.agentsTel = agentsTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.AGENTS_FAX
     *
     * @return the value of AGENTS.AGENTS_FAX
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getAgentsFax() {
        return agentsFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.AGENTS_FAX
     *
     * @param agentsFax the value for AGENTS.AGENTS_FAX
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setAgentsFax(String agentsFax) {
        this.agentsFax = agentsFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.AGENTS_MAIL
     *
     * @return the value of AGENTS.AGENTS_MAIL
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getAgentsMail() {
        return agentsMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.AGENTS_MAIL
     *
     * @param agentsMail the value for AGENTS.AGENTS_MAIL
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setAgentsMail(String agentsMail) {
        this.agentsMail = agentsMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.AGENTS_SITE
     *
     * @return the value of AGENTS.AGENTS_SITE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getAgentsSite() {
        return agentsSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.AGENTS_SITE
     *
     * @param agentsSite the value for AGENTS.AGENTS_SITE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setAgentsSite(String agentsSite) {
        this.agentsSite = agentsSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.AGENTS_ADDR
     *
     * @return the value of AGENTS.AGENTS_ADDR
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getAgentsAddr() {
        return agentsAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.AGENTS_ADDR
     *
     * @param agentsAddr the value for AGENTS.AGENTS_ADDR
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setAgentsAddr(String agentsAddr) {
        this.agentsAddr = agentsAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.ZIP_CODE
     *
     * @return the value of AGENTS.ZIP_CODE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.ZIP_CODE
     *
     * @param zipCode the value for AGENTS.ZIP_CODE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.IS_ENABLE
     *
     * @return the value of AGENTS.IS_ENABLE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.IS_ENABLE
     *
     * @param isEnable the value for AGENTS.IS_ENABLE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.AGENTS_LEVEL
     *
     * @return the value of AGENTS.AGENTS_LEVEL
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getAgentsLevel() {
        return agentsLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.AGENTS_LEVEL
     *
     * @param agentsLevel the value for AGENTS.AGENTS_LEVEL
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setAgentsLevel(String agentsLevel) {
        this.agentsLevel = agentsLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.OPERATING_RANGE
     *
     * @return the value of AGENTS.OPERATING_RANGE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getOperatingRange() {
        return operatingRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.OPERATING_RANGE
     *
     * @param operatingRange the value for AGENTS.OPERATING_RANGE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setOperatingRange(String operatingRange) {
        this.operatingRange = operatingRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.AGENT_APPLICATION_ID
     *
     * @return the value of AGENTS.AGENT_APPLICATION_ID
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public Long getAgentApplicationId() {
        return agentApplicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.AGENT_APPLICATION_ID
     *
     * @param agentApplicationId the value for AGENTS.AGENT_APPLICATION_ID
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setAgentApplicationId(Long agentApplicationId) {
        this.agentApplicationId = agentApplicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.LICENSE_NO
     *
     * @return the value of AGENTS.LICENSE_NO
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getLicenseNo() {
        return licenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.LICENSE_NO
     *
     * @param licenseNo the value for AGENTS.LICENSE_NO
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setLicenseNo(String licenseNo) {
        this.licenseNo = licenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.TYPE_OF_CONTRACT
     *
     * @return the value of AGENTS.TYPE_OF_CONTRACT
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getTypeOfContract() {
        return typeOfContract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.TYPE_OF_CONTRACT
     *
     * @param typeOfContract the value for AGENTS.TYPE_OF_CONTRACT
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setTypeOfContract(String typeOfContract) {
        this.typeOfContract = typeOfContract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.IS_SHOW_PRICES
     *
     * @return the value of AGENTS.IS_SHOW_PRICES
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getIsShowPrices() {
        return isShowPrices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.IS_SHOW_PRICES
     *
     * @param isShowPrices the value for AGENTS.IS_SHOW_PRICES
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setIsShowPrices(String isShowPrices) {
        this.isShowPrices = isShowPrices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.AGENTS_STATUS
     *
     * @return the value of AGENTS.AGENTS_STATUS
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getAgentsStatus() {
        return agentsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.AGENTS_STATUS
     *
     * @param agentsStatus the value for AGENTS.AGENTS_STATUS
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setAgentsStatus(String agentsStatus) {
        this.agentsStatus = agentsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.ACCOUNT_EXECUTIVE
     *
     * @return the value of AGENTS.ACCOUNT_EXECUTIVE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getAccountExecutive() {
        return accountExecutive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.ACCOUNT_EXECUTIVE
     *
     * @param accountExecutive the value for AGENTS.ACCOUNT_EXECUTIVE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setAccountExecutive(String accountExecutive) {
        this.accountExecutive = accountExecutive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.AGENTS_CONTACT
     *
     * @return the value of AGENTS.AGENTS_CONTACT
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getAgentsContact() {
        return agentsContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.AGENTS_CONTACT
     *
     * @param agentsContact the value for AGENTS.AGENTS_CONTACT
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setAgentsContact(String agentsContact) {
        this.agentsContact = agentsContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.CONTACT_PHONE
     *
     * @return the value of AGENTS.CONTACT_PHONE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.CONTACT_PHONE
     *
     * @param contactPhone the value for AGENTS.CONTACT_PHONE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.AGENTS_INTRODUCTION
     *
     * @return the value of AGENTS.AGENTS_INTRODUCTION
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getAgentsIntroduction() {
        return agentsIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.AGENTS_INTRODUCTION
     *
     * @param agentsIntroduction the value for AGENTS.AGENTS_INTRODUCTION
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setAgentsIntroduction(String agentsIntroduction) {
        this.agentsIntroduction = agentsIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.BASIC_INFO_AUDIT_STATUS
     *
     * @return the value of AGENTS.BASIC_INFO_AUDIT_STATUS
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getBasicInfoAuditStatus() {
        return basicInfoAuditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.BASIC_INFO_AUDIT_STATUS
     *
     * @param basicInfoAuditStatus the value for AGENTS.BASIC_INFO_AUDIT_STATUS
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setBasicInfoAuditStatus(String basicInfoAuditStatus) {
        this.basicInfoAuditStatus = basicInfoAuditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.BASIC_INFO_AUDITOR
     *
     * @return the value of AGENTS.BASIC_INFO_AUDITOR
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getBasicInfoAuditor() {
        return basicInfoAuditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.BASIC_INFO_AUDITOR
     *
     * @param basicInfoAuditor the value for AGENTS.BASIC_INFO_AUDITOR
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setBasicInfoAuditor(String basicInfoAuditor) {
        this.basicInfoAuditor = basicInfoAuditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.GMT_BASIC_INFO_AUDIT
     *
     * @return the value of AGENTS.GMT_BASIC_INFO_AUDIT
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public Date getGmtBasicInfoAudit() {
        return gmtBasicInfoAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.GMT_BASIC_INFO_AUDIT
     *
     * @param gmtBasicInfoAudit the value for AGENTS.GMT_BASIC_INFO_AUDIT
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setGmtBasicInfoAudit(Date gmtBasicInfoAudit) {
        this.gmtBasicInfoAudit = gmtBasicInfoAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.BASIC_INFO_AUDIT_OPINION
     *
     * @return the value of AGENTS.BASIC_INFO_AUDIT_OPINION
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getBasicInfoAuditOpinion() {
        return basicInfoAuditOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.BASIC_INFO_AUDIT_OPINION
     *
     * @param basicInfoAuditOpinion the value for AGENTS.BASIC_INFO_AUDIT_OPINION
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setBasicInfoAuditOpinion(String basicInfoAuditOpinion) {
        this.basicInfoAuditOpinion = basicInfoAuditOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.FINANCAIL_INFO_AUDIT_STATUS
     *
     * @return the value of AGENTS.FINANCAIL_INFO_AUDIT_STATUS
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getFinancailInfoAuditStatus() {
        return financailInfoAuditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.FINANCAIL_INFO_AUDIT_STATUS
     *
     * @param financailInfoAuditStatus the value for AGENTS.FINANCAIL_INFO_AUDIT_STATUS
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setFinancailInfoAuditStatus(String financailInfoAuditStatus) {
        this.financailInfoAuditStatus = financailInfoAuditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.FINANCAIL_INFO_AUDITOR
     *
     * @return the value of AGENTS.FINANCAIL_INFO_AUDITOR
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getFinancailInfoAuditor() {
        return financailInfoAuditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.FINANCAIL_INFO_AUDITOR
     *
     * @param financailInfoAuditor the value for AGENTS.FINANCAIL_INFO_AUDITOR
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setFinancailInfoAuditor(String financailInfoAuditor) {
        this.financailInfoAuditor = financailInfoAuditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.GMT_FINANCAIL_INFO_AUDIT
     *
     * @return the value of AGENTS.GMT_FINANCAIL_INFO_AUDIT
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public Date getGmtFinancailInfoAudit() {
        return gmtFinancailInfoAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.GMT_FINANCAIL_INFO_AUDIT
     *
     * @param gmtFinancailInfoAudit the value for AGENTS.GMT_FINANCAIL_INFO_AUDIT
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setGmtFinancailInfoAudit(Date gmtFinancailInfoAudit) {
        this.gmtFinancailInfoAudit = gmtFinancailInfoAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.FINANCAIL_INFO_AUDIT_OPINION
     *
     * @return the value of AGENTS.FINANCAIL_INFO_AUDIT_OPINION
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getFinancailInfoAuditOpinion() {
        return financailInfoAuditOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.FINANCAIL_INFO_AUDIT_OPINION
     *
     * @param financailInfoAuditOpinion the value for AGENTS.FINANCAIL_INFO_AUDIT_OPINION
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setFinancailInfoAuditOpinion(String financailInfoAuditOpinion) {
        this.financailInfoAuditOpinion = financailInfoAuditOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.CREATOR
     *
     * @return the value of AGENTS.CREATOR
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.CREATOR
     *
     * @param creator the value for AGENTS.CREATOR
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.GMT_CREATE
     *
     * @return the value of AGENTS.GMT_CREATE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.GMT_CREATE
     *
     * @param gmtCreate the value for AGENTS.GMT_CREATE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.MODIFIER
     *
     * @return the value of AGENTS.MODIFIER
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.MODIFIER
     *
     * @param modifier the value for AGENTS.MODIFIER
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.GMT_MODIFY
     *
     * @return the value of AGENTS.GMT_MODIFY
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.GMT_MODIFY
     *
     * @param gmtModify the value for AGENTS.GMT_MODIFY
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.IS_EDIT
     *
     * @return the value of AGENTS.IS_EDIT
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public Boolean getIsEdit() {
        return isEdit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.IS_EDIT
     *
     * @param isEdit the value for AGENTS.IS_EDIT
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setIsEdit(Boolean isEdit) {
        this.isEdit = isEdit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.IS_CREDIT
     *
     * @return the value of AGENTS.IS_CREDIT
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public Boolean getIsCredit() {
        return isCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.IS_CREDIT
     *
     * @param isCredit the value for AGENTS.IS_CREDIT
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setIsCredit(Boolean isCredit) {
        this.isCredit = isCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.IS_LIMIT_BOOKING
     *
     * @return the value of AGENTS.IS_LIMIT_BOOKING
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public Boolean getIsLimitBooking() {
        return isLimitBooking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.IS_LIMIT_BOOKING
     *
     * @param isLimitBooking the value for AGENTS.IS_LIMIT_BOOKING
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setIsLimitBooking(Boolean isLimitBooking) {
        this.isLimitBooking = isLimitBooking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.LEGAL_REPRESENTATIVE
     *
     * @return the value of AGENTS.LEGAL_REPRESENTATIVE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getLegalRepresentative() {
        return legalRepresentative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.LEGAL_REPRESENTATIVE
     *
     * @param legalRepresentative the value for AGENTS.LEGAL_REPRESENTATIVE
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setLegalRepresentative(String legalRepresentative) {
        this.legalRepresentative = legalRepresentative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.AGENTS_SIMPLE_NAME
     *
     * @return the value of AGENTS.AGENTS_SIMPLE_NAME
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public String getAgentsSimpleName() {
        return agentsSimpleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.AGENTS_SIMPLE_NAME
     *
     * @param agentsSimpleName the value for AGENTS.AGENTS_SIMPLE_NAME
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setAgentsSimpleName(String agentsSimpleName) {
        this.agentsSimpleName = agentsSimpleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AGENTS.IS_PRINT
     *
     * @return the value of AGENTS.IS_PRINT
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public Boolean getIsPrint() {
        return isPrint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AGENTS.IS_PRINT
     *
     * @param isPrint the value for AGENTS.IS_PRINT
     *
     * @mbggenerated Tue Aug 20 23:22:47 CST 2013
     */
    public void setIsPrint(Boolean isPrint) {
        this.isPrint = isPrint;
    }
}