package com.youlema.sales.mapper.meta;

import java.util.Date;

import com.youlema.sales.meta.BusinessType;

public class AgentsFavorites {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column AGENTS_FAVORITES.AGENTS_FAVORITES_ID
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    private Long agentsFavoritesId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column AGENTS_FAVORITES.AGENTS_ACCOUNT_ID
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    private Long agentsAccountId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column AGENTS_FAVORITES.GMT_OF_FAVORITES
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    private Date gmtOfFavorites;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column AGENTS_FAVORITES.MEMO
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    private String memo;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column AGENTS_FAVORITES.BUSINESS_ID
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    private Long businessId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column AGENTS_FAVORITES.BUSINESS_TYPE
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    private String businessType;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column AGENTS_FAVORITES.AGENTS_FAVORITES_ID
     * @return  the value of AGENTS_FAVORITES.AGENTS_FAVORITES_ID
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    public Long getAgentsFavoritesId() {
        return agentsFavoritesId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column AGENTS_FAVORITES.AGENTS_FAVORITES_ID
     * @param agentsFavoritesId  the value for AGENTS_FAVORITES.AGENTS_FAVORITES_ID
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    public void setAgentsFavoritesId(Long agentsFavoritesId) {
        this.agentsFavoritesId = agentsFavoritesId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column AGENTS_FAVORITES.AGENTS_ACCOUNT_ID
     * @return  the value of AGENTS_FAVORITES.AGENTS_ACCOUNT_ID
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    public Long getAgentsAccountId() {
        return agentsAccountId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column AGENTS_FAVORITES.AGENTS_ACCOUNT_ID
     * @param agentsAccountId  the value for AGENTS_FAVORITES.AGENTS_ACCOUNT_ID
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    public void setAgentsAccountId(Long agentsAccountId) {
        this.agentsAccountId = agentsAccountId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column AGENTS_FAVORITES.GMT_OF_FAVORITES
     * @return  the value of AGENTS_FAVORITES.GMT_OF_FAVORITES
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    public Date getGmtOfFavorites() {
        return gmtOfFavorites;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column AGENTS_FAVORITES.GMT_OF_FAVORITES
     * @param gmtOfFavorites  the value for AGENTS_FAVORITES.GMT_OF_FAVORITES
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    public void setGmtOfFavorites(Date gmtOfFavorites) {
        this.gmtOfFavorites = gmtOfFavorites;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column AGENTS_FAVORITES.MEMO
     * @return  the value of AGENTS_FAVORITES.MEMO
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column AGENTS_FAVORITES.MEMO
     * @param memo  the value for AGENTS_FAVORITES.MEMO
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column AGENTS_FAVORITES.BUSINESS_ID
     * @return  the value of AGENTS_FAVORITES.BUSINESS_ID
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column AGENTS_FAVORITES.BUSINESS_ID
     * @param businessId  the value for AGENTS_FAVORITES.BUSINESS_ID
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column AGENTS_FAVORITES.BUSINESS_TYPE
     * @return  the value of AGENTS_FAVORITES.BUSINESS_TYPE
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column AGENTS_FAVORITES.BUSINESS_TYPE
     * @param businessType  the value for AGENTS_FAVORITES.BUSINESS_TYPE
     * @mbggenerated  Tue Sep 03 21:59:41 CST 2013
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }

    private TourLine tourLine;

    public TourLine getTourLine() {
        return tourLine;
    }

    public void setTourLine(TourLine tourLine) {
        this.tourLine = tourLine;
    }

    public BusinessType getBusinessTypeObject() {
        return BusinessType.valueOf(businessType);
    }

}