package com.youlema.sales.mapper.meta;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AgentsPaymentFactExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table AGENTS_PAYMENT_FACT
     * @mbggenerated  Sun Aug 25 22:40:06 CST 2013
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table AGENTS_PAYMENT_FACT
     * @mbggenerated  Sun Aug 25 22:40:06 CST 2013
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table AGENTS_PAYMENT_FACT
     * @mbggenerated  Sun Aug 25 22:40:06 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_PAYMENT_FACT
     * @mbggenerated  Sun Aug 25 22:40:06 CST 2013
     */
    public AgentsPaymentFactExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_PAYMENT_FACT
     * @mbggenerated  Sun Aug 25 22:40:06 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_PAYMENT_FACT
     * @mbggenerated  Sun Aug 25 22:40:06 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_PAYMENT_FACT
     * @mbggenerated  Sun Aug 25 22:40:06 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_PAYMENT_FACT
     * @mbggenerated  Sun Aug 25 22:40:06 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_PAYMENT_FACT
     * @mbggenerated  Sun Aug 25 22:40:06 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_PAYMENT_FACT
     * @mbggenerated  Sun Aug 25 22:40:06 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_PAYMENT_FACT
     * @mbggenerated  Sun Aug 25 22:40:06 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_PAYMENT_FACT
     * @mbggenerated  Sun Aug 25 22:40:06 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_PAYMENT_FACT
     * @mbggenerated  Sun Aug 25 22:40:06 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table AGENTS_PAYMENT_FACT
     * @mbggenerated  Sun Aug 25 22:40:06 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table AGENTS_PAYMENT_FACT
     * @mbggenerated  Sun Aug 25 22:40:06 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAgentsPaymentFactIdIsNull() {
            addCriterion("AGENTS_PAYMENT_FACT_ID is null");
            return (Criteria) this;
        }

        public Criteria andAgentsPaymentFactIdIsNotNull() {
            addCriterion("AGENTS_PAYMENT_FACT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAgentsPaymentFactIdEqualTo(Long value) {
            addCriterion("AGENTS_PAYMENT_FACT_ID =", value, "agentsPaymentFactId");
            return (Criteria) this;
        }

        public Criteria andAgentsPaymentFactIdNotEqualTo(Long value) {
            addCriterion("AGENTS_PAYMENT_FACT_ID <>", value, "agentsPaymentFactId");
            return (Criteria) this;
        }

        public Criteria andAgentsPaymentFactIdGreaterThan(Long value) {
            addCriterion("AGENTS_PAYMENT_FACT_ID >", value, "agentsPaymentFactId");
            return (Criteria) this;
        }

        public Criteria andAgentsPaymentFactIdGreaterThanOrEqualTo(Long value) {
            addCriterion("AGENTS_PAYMENT_FACT_ID >=", value, "agentsPaymentFactId");
            return (Criteria) this;
        }

        public Criteria andAgentsPaymentFactIdLessThan(Long value) {
            addCriterion("AGENTS_PAYMENT_FACT_ID <", value, "agentsPaymentFactId");
            return (Criteria) this;
        }

        public Criteria andAgentsPaymentFactIdLessThanOrEqualTo(Long value) {
            addCriterion("AGENTS_PAYMENT_FACT_ID <=", value, "agentsPaymentFactId");
            return (Criteria) this;
        }

        public Criteria andAgentsPaymentFactIdIn(List<Long> values) {
            addCriterion("AGENTS_PAYMENT_FACT_ID in", values, "agentsPaymentFactId");
            return (Criteria) this;
        }

        public Criteria andAgentsPaymentFactIdNotIn(List<Long> values) {
            addCriterion("AGENTS_PAYMENT_FACT_ID not in", values, "agentsPaymentFactId");
            return (Criteria) this;
        }

        public Criteria andAgentsPaymentFactIdBetween(Long value1, Long value2) {
            addCriterion("AGENTS_PAYMENT_FACT_ID between", value1, value2, "agentsPaymentFactId");
            return (Criteria) this;
        }

        public Criteria andAgentsPaymentFactIdNotBetween(Long value1, Long value2) {
            addCriterion("AGENTS_PAYMENT_FACT_ID not between", value1, value2, "agentsPaymentFactId");
            return (Criteria) this;
        }

        public Criteria andAgentsIdIsNull() {
            addCriterion("AGENTS_ID is null");
            return (Criteria) this;
        }

        public Criteria andAgentsIdIsNotNull() {
            addCriterion("AGENTS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAgentsIdEqualTo(Long value) {
            addCriterion("AGENTS_ID =", value, "agentsId");
            return (Criteria) this;
        }

        public Criteria andAgentsIdNotEqualTo(Long value) {
            addCriterion("AGENTS_ID <>", value, "agentsId");
            return (Criteria) this;
        }

        public Criteria andAgentsIdGreaterThan(Long value) {
            addCriterion("AGENTS_ID >", value, "agentsId");
            return (Criteria) this;
        }

        public Criteria andAgentsIdGreaterThanOrEqualTo(Long value) {
            addCriterion("AGENTS_ID >=", value, "agentsId");
            return (Criteria) this;
        }

        public Criteria andAgentsIdLessThan(Long value) {
            addCriterion("AGENTS_ID <", value, "agentsId");
            return (Criteria) this;
        }

        public Criteria andAgentsIdLessThanOrEqualTo(Long value) {
            addCriterion("AGENTS_ID <=", value, "agentsId");
            return (Criteria) this;
        }

        public Criteria andAgentsIdIn(List<Long> values) {
            addCriterion("AGENTS_ID in", values, "agentsId");
            return (Criteria) this;
        }

        public Criteria andAgentsIdNotIn(List<Long> values) {
            addCriterion("AGENTS_ID not in", values, "agentsId");
            return (Criteria) this;
        }

        public Criteria andAgentsIdBetween(Long value1, Long value2) {
            addCriterion("AGENTS_ID between", value1, value2, "agentsId");
            return (Criteria) this;
        }

        public Criteria andAgentsIdNotBetween(Long value1, Long value2) {
            addCriterion("AGENTS_ID not between", value1, value2, "agentsId");
            return (Criteria) this;
        }

        public Criteria andOrderBillIdIsNull() {
            addCriterion("ORDER_BILL_ID is null");
            return (Criteria) this;
        }

        public Criteria andOrderBillIdIsNotNull() {
            addCriterion("ORDER_BILL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOrderBillIdEqualTo(Long value) {
            addCriterion("ORDER_BILL_ID =", value, "orderBillId");
            return (Criteria) this;
        }

        public Criteria andOrderBillIdNotEqualTo(Long value) {
            addCriterion("ORDER_BILL_ID <>", value, "orderBillId");
            return (Criteria) this;
        }

        public Criteria andOrderBillIdGreaterThan(Long value) {
            addCriterion("ORDER_BILL_ID >", value, "orderBillId");
            return (Criteria) this;
        }

        public Criteria andOrderBillIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ORDER_BILL_ID >=", value, "orderBillId");
            return (Criteria) this;
        }

        public Criteria andOrderBillIdLessThan(Long value) {
            addCriterion("ORDER_BILL_ID <", value, "orderBillId");
            return (Criteria) this;
        }

        public Criteria andOrderBillIdLessThanOrEqualTo(Long value) {
            addCriterion("ORDER_BILL_ID <=", value, "orderBillId");
            return (Criteria) this;
        }

        public Criteria andOrderBillIdIn(List<Long> values) {
            addCriterion("ORDER_BILL_ID in", values, "orderBillId");
            return (Criteria) this;
        }

        public Criteria andOrderBillIdNotIn(List<Long> values) {
            addCriterion("ORDER_BILL_ID not in", values, "orderBillId");
            return (Criteria) this;
        }

        public Criteria andOrderBillIdBetween(Long value1, Long value2) {
            addCriterion("ORDER_BILL_ID between", value1, value2, "orderBillId");
            return (Criteria) this;
        }

        public Criteria andOrderBillIdNotBetween(Long value1, Long value2) {
            addCriterion("ORDER_BILL_ID not between", value1, value2, "orderBillId");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("PRODUCT_ID is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("PRODUCT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Long value) {
            addCriterion("PRODUCT_ID =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Long value) {
            addCriterion("PRODUCT_ID <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Long value) {
            addCriterion("PRODUCT_ID >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PRODUCT_ID >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Long value) {
            addCriterion("PRODUCT_ID <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Long value) {
            addCriterion("PRODUCT_ID <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Long> values) {
            addCriterion("PRODUCT_ID in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Long> values) {
            addCriterion("PRODUCT_ID not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Long value1, Long value2) {
            addCriterion("PRODUCT_ID between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Long value1, Long value2) {
            addCriterion("PRODUCT_ID not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductNoIsNull() {
            addCriterion("PRODUCT_NO is null");
            return (Criteria) this;
        }

        public Criteria andProductNoIsNotNull() {
            addCriterion("PRODUCT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andProductNoEqualTo(String value) {
            addCriterion("PRODUCT_NO =", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotEqualTo(String value) {
            addCriterion("PRODUCT_NO <>", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoGreaterThan(String value) {
            addCriterion("PRODUCT_NO >", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_NO >=", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoLessThan(String value) {
            addCriterion("PRODUCT_NO <", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_NO <=", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoLike(String value) {
            addCriterion("PRODUCT_NO like", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotLike(String value) {
            addCriterion("PRODUCT_NO not like", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoIn(List<String> values) {
            addCriterion("PRODUCT_NO in", values, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotIn(List<String> values) {
            addCriterion("PRODUCT_NO not in", values, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoBetween(String value1, String value2) {
            addCriterion("PRODUCT_NO between", value1, value2, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_NO not between", value1, value2, "productNo");
            return (Criteria) this;
        }

        public Criteria andOrderCodeIsNull() {
            addCriterion("ORDER_CODE is null");
            return (Criteria) this;
        }

        public Criteria andOrderCodeIsNotNull() {
            addCriterion("ORDER_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andOrderCodeEqualTo(String value) {
            addCriterion("ORDER_CODE =", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeNotEqualTo(String value) {
            addCriterion("ORDER_CODE <>", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeGreaterThan(String value) {
            addCriterion("ORDER_CODE >", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_CODE >=", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeLessThan(String value) {
            addCriterion("ORDER_CODE <", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeLessThanOrEqualTo(String value) {
            addCriterion("ORDER_CODE <=", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeLike(String value) {
            addCriterion("ORDER_CODE like", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeNotLike(String value) {
            addCriterion("ORDER_CODE not like", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeIn(List<String> values) {
            addCriterion("ORDER_CODE in", values, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeNotIn(List<String> values) {
            addCriterion("ORDER_CODE not in", values, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeBetween(String value1, String value2) {
            addCriterion("ORDER_CODE between", value1, value2, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeNotBetween(String value1, String value2) {
            addCriterion("ORDER_CODE not between", value1, value2, "orderCode");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("PRODUCT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("PRODUCT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("PRODUCT_NAME =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("PRODUCT_NAME <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("PRODUCT_NAME >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_NAME >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("PRODUCT_NAME <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_NAME <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("PRODUCT_NAME like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("PRODUCT_NAME not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("PRODUCT_NAME in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("PRODUCT_NAME not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("PRODUCT_NAME between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_NAME not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andGmtDayOfStartIsNull() {
            addCriterion("GMT_DAY_OF_START is null");
            return (Criteria) this;
        }

        public Criteria andGmtDayOfStartIsNotNull() {
            addCriterion("GMT_DAY_OF_START is not null");
            return (Criteria) this;
        }

        public Criteria andGmtDayOfStartEqualTo(Date value) {
            addCriterion("GMT_DAY_OF_START =", value, "gmtDayOfStart");
            return (Criteria) this;
        }

        public Criteria andGmtDayOfStartNotEqualTo(Date value) {
            addCriterion("GMT_DAY_OF_START <>", value, "gmtDayOfStart");
            return (Criteria) this;
        }

        public Criteria andGmtDayOfStartGreaterThan(Date value) {
            addCriterion("GMT_DAY_OF_START >", value, "gmtDayOfStart");
            return (Criteria) this;
        }

        public Criteria andGmtDayOfStartGreaterThanOrEqualTo(Date value) {
            addCriterion("GMT_DAY_OF_START >=", value, "gmtDayOfStart");
            return (Criteria) this;
        }

        public Criteria andGmtDayOfStartLessThan(Date value) {
            addCriterion("GMT_DAY_OF_START <", value, "gmtDayOfStart");
            return (Criteria) this;
        }

        public Criteria andGmtDayOfStartLessThanOrEqualTo(Date value) {
            addCriterion("GMT_DAY_OF_START <=", value, "gmtDayOfStart");
            return (Criteria) this;
        }

        public Criteria andGmtDayOfStartIn(List<Date> values) {
            addCriterion("GMT_DAY_OF_START in", values, "gmtDayOfStart");
            return (Criteria) this;
        }

        public Criteria andGmtDayOfStartNotIn(List<Date> values) {
            addCriterion("GMT_DAY_OF_START not in", values, "gmtDayOfStart");
            return (Criteria) this;
        }

        public Criteria andGmtDayOfStartBetween(Date value1, Date value2) {
            addCriterion("GMT_DAY_OF_START between", value1, value2, "gmtDayOfStart");
            return (Criteria) this;
        }

        public Criteria andGmtDayOfStartNotBetween(Date value1, Date value2) {
            addCriterion("GMT_DAY_OF_START not between", value1, value2, "gmtDayOfStart");
            return (Criteria) this;
        }

        public Criteria andOrderAmountIsNull() {
            addCriterion("ORDER_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andOrderAmountIsNotNull() {
            addCriterion("ORDER_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andOrderAmountEqualTo(BigDecimal value) {
            addCriterion("ORDER_AMOUNT =", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountNotEqualTo(BigDecimal value) {
            addCriterion("ORDER_AMOUNT <>", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountGreaterThan(BigDecimal value) {
            addCriterion("ORDER_AMOUNT >", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ORDER_AMOUNT >=", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountLessThan(BigDecimal value) {
            addCriterion("ORDER_AMOUNT <", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ORDER_AMOUNT <=", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountIn(List<BigDecimal> values) {
            addCriterion("ORDER_AMOUNT in", values, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountNotIn(List<BigDecimal> values) {
            addCriterion("ORDER_AMOUNT not in", values, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORDER_AMOUNT between", value1, value2, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORDER_AMOUNT not between", value1, value2, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andSettlementAmountIsNull() {
            addCriterion("SETTLEMENT_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andSettlementAmountIsNotNull() {
            addCriterion("SETTLEMENT_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andSettlementAmountEqualTo(BigDecimal value) {
            addCriterion("SETTLEMENT_AMOUNT =", value, "settlementAmount");
            return (Criteria) this;
        }

        public Criteria andSettlementAmountNotEqualTo(BigDecimal value) {
            addCriterion("SETTLEMENT_AMOUNT <>", value, "settlementAmount");
            return (Criteria) this;
        }

        public Criteria andSettlementAmountGreaterThan(BigDecimal value) {
            addCriterion("SETTLEMENT_AMOUNT >", value, "settlementAmount");
            return (Criteria) this;
        }

        public Criteria andSettlementAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SETTLEMENT_AMOUNT >=", value, "settlementAmount");
            return (Criteria) this;
        }

        public Criteria andSettlementAmountLessThan(BigDecimal value) {
            addCriterion("SETTLEMENT_AMOUNT <", value, "settlementAmount");
            return (Criteria) this;
        }

        public Criteria andSettlementAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SETTLEMENT_AMOUNT <=", value, "settlementAmount");
            return (Criteria) this;
        }

        public Criteria andSettlementAmountIn(List<BigDecimal> values) {
            addCriterion("SETTLEMENT_AMOUNT in", values, "settlementAmount");
            return (Criteria) this;
        }

        public Criteria andSettlementAmountNotIn(List<BigDecimal> values) {
            addCriterion("SETTLEMENT_AMOUNT not in", values, "settlementAmount");
            return (Criteria) this;
        }

        public Criteria andSettlementAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SETTLEMENT_AMOUNT between", value1, value2, "settlementAmount");
            return (Criteria) this;
        }

        public Criteria andSettlementAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SETTLEMENT_AMOUNT not between", value1, value2, "settlementAmount");
            return (Criteria) this;
        }

        public Criteria andPaidAmountIsNull() {
            addCriterion("PAID_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andPaidAmountIsNotNull() {
            addCriterion("PAID_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andPaidAmountEqualTo(BigDecimal value) {
            addCriterion("PAID_AMOUNT =", value, "paidAmount");
            return (Criteria) this;
        }

        public Criteria andPaidAmountNotEqualTo(BigDecimal value) {
            addCriterion("PAID_AMOUNT <>", value, "paidAmount");
            return (Criteria) this;
        }

        public Criteria andPaidAmountGreaterThan(BigDecimal value) {
            addCriterion("PAID_AMOUNT >", value, "paidAmount");
            return (Criteria) this;
        }

        public Criteria andPaidAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAID_AMOUNT >=", value, "paidAmount");
            return (Criteria) this;
        }

        public Criteria andPaidAmountLessThan(BigDecimal value) {
            addCriterion("PAID_AMOUNT <", value, "paidAmount");
            return (Criteria) this;
        }

        public Criteria andPaidAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAID_AMOUNT <=", value, "paidAmount");
            return (Criteria) this;
        }

        public Criteria andPaidAmountIn(List<BigDecimal> values) {
            addCriterion("PAID_AMOUNT in", values, "paidAmount");
            return (Criteria) this;
        }

        public Criteria andPaidAmountNotIn(List<BigDecimal> values) {
            addCriterion("PAID_AMOUNT not in", values, "paidAmount");
            return (Criteria) this;
        }

        public Criteria andPaidAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAID_AMOUNT between", value1, value2, "paidAmount");
            return (Criteria) this;
        }

        public Criteria andPaidAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAID_AMOUNT not between", value1, value2, "paidAmount");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountIsNull() {
            addCriterion("UNPAID_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountIsNotNull() {
            addCriterion("UNPAID_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountEqualTo(BigDecimal value) {
            addCriterion("UNPAID_AMOUNT =", value, "unpaidAmount");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountNotEqualTo(BigDecimal value) {
            addCriterion("UNPAID_AMOUNT <>", value, "unpaidAmount");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountGreaterThan(BigDecimal value) {
            addCriterion("UNPAID_AMOUNT >", value, "unpaidAmount");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("UNPAID_AMOUNT >=", value, "unpaidAmount");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountLessThan(BigDecimal value) {
            addCriterion("UNPAID_AMOUNT <", value, "unpaidAmount");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("UNPAID_AMOUNT <=", value, "unpaidAmount");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountIn(List<BigDecimal> values) {
            addCriterion("UNPAID_AMOUNT in", values, "unpaidAmount");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountNotIn(List<BigDecimal> values) {
            addCriterion("UNPAID_AMOUNT not in", values, "unpaidAmount");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UNPAID_AMOUNT between", value1, value2, "unpaidAmount");
            return (Criteria) this;
        }

        public Criteria andUnpaidAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UNPAID_AMOUNT not between", value1, value2, "unpaidAmount");
            return (Criteria) this;
        }

        public Criteria andGmtDeadlineIsNull() {
            addCriterion("GMT_DEADLINE is null");
            return (Criteria) this;
        }

        public Criteria andGmtDeadlineIsNotNull() {
            addCriterion("GMT_DEADLINE is not null");
            return (Criteria) this;
        }

        public Criteria andGmtDeadlineEqualTo(Date value) {
            addCriterion("GMT_DEADLINE =", value, "gmtDeadline");
            return (Criteria) this;
        }

        public Criteria andGmtDeadlineNotEqualTo(Date value) {
            addCriterion("GMT_DEADLINE <>", value, "gmtDeadline");
            return (Criteria) this;
        }

        public Criteria andGmtDeadlineGreaterThan(Date value) {
            addCriterion("GMT_DEADLINE >", value, "gmtDeadline");
            return (Criteria) this;
        }

        public Criteria andGmtDeadlineGreaterThanOrEqualTo(Date value) {
            addCriterion("GMT_DEADLINE >=", value, "gmtDeadline");
            return (Criteria) this;
        }

        public Criteria andGmtDeadlineLessThan(Date value) {
            addCriterion("GMT_DEADLINE <", value, "gmtDeadline");
            return (Criteria) this;
        }

        public Criteria andGmtDeadlineLessThanOrEqualTo(Date value) {
            addCriterion("GMT_DEADLINE <=", value, "gmtDeadline");
            return (Criteria) this;
        }

        public Criteria andGmtDeadlineIn(List<Date> values) {
            addCriterion("GMT_DEADLINE in", values, "gmtDeadline");
            return (Criteria) this;
        }

        public Criteria andGmtDeadlineNotIn(List<Date> values) {
            addCriterion("GMT_DEADLINE not in", values, "gmtDeadline");
            return (Criteria) this;
        }

        public Criteria andGmtDeadlineBetween(Date value1, Date value2) {
            addCriterion("GMT_DEADLINE between", value1, value2, "gmtDeadline");
            return (Criteria) this;
        }

        public Criteria andGmtDeadlineNotBetween(Date value1, Date value2) {
            addCriterion("GMT_DEADLINE not between", value1, value2, "gmtDeadline");
            return (Criteria) this;
        }

        public Criteria andMainTypeCodeIsNull() {
            addCriterion("MAIN_TYPE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andMainTypeCodeIsNotNull() {
            addCriterion("MAIN_TYPE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andMainTypeCodeEqualTo(String value) {
            addCriterion("MAIN_TYPE_CODE =", value, "mainTypeCode");
            return (Criteria) this;
        }

        public Criteria andMainTypeCodeNotEqualTo(String value) {
            addCriterion("MAIN_TYPE_CODE <>", value, "mainTypeCode");
            return (Criteria) this;
        }

        public Criteria andMainTypeCodeGreaterThan(String value) {
            addCriterion("MAIN_TYPE_CODE >", value, "mainTypeCode");
            return (Criteria) this;
        }

        public Criteria andMainTypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("MAIN_TYPE_CODE >=", value, "mainTypeCode");
            return (Criteria) this;
        }

        public Criteria andMainTypeCodeLessThan(String value) {
            addCriterion("MAIN_TYPE_CODE <", value, "mainTypeCode");
            return (Criteria) this;
        }

        public Criteria andMainTypeCodeLessThanOrEqualTo(String value) {
            addCriterion("MAIN_TYPE_CODE <=", value, "mainTypeCode");
            return (Criteria) this;
        }

        public Criteria andMainTypeCodeLike(String value) {
            addCriterion("MAIN_TYPE_CODE like", value, "mainTypeCode");
            return (Criteria) this;
        }

        public Criteria andMainTypeCodeNotLike(String value) {
            addCriterion("MAIN_TYPE_CODE not like", value, "mainTypeCode");
            return (Criteria) this;
        }

        public Criteria andMainTypeCodeIn(List<String> values) {
            addCriterion("MAIN_TYPE_CODE in", values, "mainTypeCode");
            return (Criteria) this;
        }

        public Criteria andMainTypeCodeNotIn(List<String> values) {
            addCriterion("MAIN_TYPE_CODE not in", values, "mainTypeCode");
            return (Criteria) this;
        }

        public Criteria andMainTypeCodeBetween(String value1, String value2) {
            addCriterion("MAIN_TYPE_CODE between", value1, value2, "mainTypeCode");
            return (Criteria) this;
        }

        public Criteria andMainTypeCodeNotBetween(String value1, String value2) {
            addCriterion("MAIN_TYPE_CODE not between", value1, value2, "mainTypeCode");
            return (Criteria) this;
        }

        public Criteria andMinorTypeCodeIsNull() {
            addCriterion("MINOR_TYPE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andMinorTypeCodeIsNotNull() {
            addCriterion("MINOR_TYPE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andMinorTypeCodeEqualTo(String value) {
            addCriterion("MINOR_TYPE_CODE =", value, "minorTypeCode");
            return (Criteria) this;
        }

        public Criteria andMinorTypeCodeNotEqualTo(String value) {
            addCriterion("MINOR_TYPE_CODE <>", value, "minorTypeCode");
            return (Criteria) this;
        }

        public Criteria andMinorTypeCodeGreaterThan(String value) {
            addCriterion("MINOR_TYPE_CODE >", value, "minorTypeCode");
            return (Criteria) this;
        }

        public Criteria andMinorTypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("MINOR_TYPE_CODE >=", value, "minorTypeCode");
            return (Criteria) this;
        }

        public Criteria andMinorTypeCodeLessThan(String value) {
            addCriterion("MINOR_TYPE_CODE <", value, "minorTypeCode");
            return (Criteria) this;
        }

        public Criteria andMinorTypeCodeLessThanOrEqualTo(String value) {
            addCriterion("MINOR_TYPE_CODE <=", value, "minorTypeCode");
            return (Criteria) this;
        }

        public Criteria andMinorTypeCodeLike(String value) {
            addCriterion("MINOR_TYPE_CODE like", value, "minorTypeCode");
            return (Criteria) this;
        }

        public Criteria andMinorTypeCodeNotLike(String value) {
            addCriterion("MINOR_TYPE_CODE not like", value, "minorTypeCode");
            return (Criteria) this;
        }

        public Criteria andMinorTypeCodeIn(List<String> values) {
            addCriterion("MINOR_TYPE_CODE in", values, "minorTypeCode");
            return (Criteria) this;
        }

        public Criteria andMinorTypeCodeNotIn(List<String> values) {
            addCriterion("MINOR_TYPE_CODE not in", values, "minorTypeCode");
            return (Criteria) this;
        }

        public Criteria andMinorTypeCodeBetween(String value1, String value2) {
            addCriterion("MINOR_TYPE_CODE between", value1, value2, "minorTypeCode");
            return (Criteria) this;
        }

        public Criteria andMinorTypeCodeNotBetween(String value1, String value2) {
            addCriterion("MINOR_TYPE_CODE not between", value1, value2, "minorTypeCode");
            return (Criteria) this;
        }

        public Criteria andTotalAdultIsNull() {
            addCriterion("TOTAL_ADULT is null");
            return (Criteria) this;
        }

        public Criteria andTotalAdultIsNotNull() {
            addCriterion("TOTAL_ADULT is not null");
            return (Criteria) this;
        }

        public Criteria andTotalAdultEqualTo(Integer value) {
            addCriterion("TOTAL_ADULT =", value, "totalAdult");
            return (Criteria) this;
        }

        public Criteria andTotalAdultNotEqualTo(Integer value) {
            addCriterion("TOTAL_ADULT <>", value, "totalAdult");
            return (Criteria) this;
        }

        public Criteria andTotalAdultGreaterThan(Integer value) {
            addCriterion("TOTAL_ADULT >", value, "totalAdult");
            return (Criteria) this;
        }

        public Criteria andTotalAdultGreaterThanOrEqualTo(Integer value) {
            addCriterion("TOTAL_ADULT >=", value, "totalAdult");
            return (Criteria) this;
        }

        public Criteria andTotalAdultLessThan(Integer value) {
            addCriterion("TOTAL_ADULT <", value, "totalAdult");
            return (Criteria) this;
        }

        public Criteria andTotalAdultLessThanOrEqualTo(Integer value) {
            addCriterion("TOTAL_ADULT <=", value, "totalAdult");
            return (Criteria) this;
        }

        public Criteria andTotalAdultIn(List<Integer> values) {
            addCriterion("TOTAL_ADULT in", values, "totalAdult");
            return (Criteria) this;
        }

        public Criteria andTotalAdultNotIn(List<Integer> values) {
            addCriterion("TOTAL_ADULT not in", values, "totalAdult");
            return (Criteria) this;
        }

        public Criteria andTotalAdultBetween(Integer value1, Integer value2) {
            addCriterion("TOTAL_ADULT between", value1, value2, "totalAdult");
            return (Criteria) this;
        }

        public Criteria andTotalAdultNotBetween(Integer value1, Integer value2) {
            addCriterion("TOTAL_ADULT not between", value1, value2, "totalAdult");
            return (Criteria) this;
        }

        public Criteria andTotalChildIsNull() {
            addCriterion("TOTAL_CHILD is null");
            return (Criteria) this;
        }

        public Criteria andTotalChildIsNotNull() {
            addCriterion("TOTAL_CHILD is not null");
            return (Criteria) this;
        }

        public Criteria andTotalChildEqualTo(Integer value) {
            addCriterion("TOTAL_CHILD =", value, "totalChild");
            return (Criteria) this;
        }

        public Criteria andTotalChildNotEqualTo(Integer value) {
            addCriterion("TOTAL_CHILD <>", value, "totalChild");
            return (Criteria) this;
        }

        public Criteria andTotalChildGreaterThan(Integer value) {
            addCriterion("TOTAL_CHILD >", value, "totalChild");
            return (Criteria) this;
        }

        public Criteria andTotalChildGreaterThanOrEqualTo(Integer value) {
            addCriterion("TOTAL_CHILD >=", value, "totalChild");
            return (Criteria) this;
        }

        public Criteria andTotalChildLessThan(Integer value) {
            addCriterion("TOTAL_CHILD <", value, "totalChild");
            return (Criteria) this;
        }

        public Criteria andTotalChildLessThanOrEqualTo(Integer value) {
            addCriterion("TOTAL_CHILD <=", value, "totalChild");
            return (Criteria) this;
        }

        public Criteria andTotalChildIn(List<Integer> values) {
            addCriterion("TOTAL_CHILD in", values, "totalChild");
            return (Criteria) this;
        }

        public Criteria andTotalChildNotIn(List<Integer> values) {
            addCriterion("TOTAL_CHILD not in", values, "totalChild");
            return (Criteria) this;
        }

        public Criteria andTotalChildBetween(Integer value1, Integer value2) {
            addCriterion("TOTAL_CHILD between", value1, value2, "totalChild");
            return (Criteria) this;
        }

        public Criteria andTotalChildNotBetween(Integer value1, Integer value2) {
            addCriterion("TOTAL_CHILD not between", value1, value2, "totalChild");
            return (Criteria) this;
        }

        public Criteria andYearOfStartIsNull() {
            addCriterion("YEAR_OF_START is null");
            return (Criteria) this;
        }

        public Criteria andYearOfStartIsNotNull() {
            addCriterion("YEAR_OF_START is not null");
            return (Criteria) this;
        }

        public Criteria andYearOfStartEqualTo(Integer value) {
            addCriterion("YEAR_OF_START =", value, "yearOfStart");
            return (Criteria) this;
        }

        public Criteria andYearOfStartNotEqualTo(Integer value) {
            addCriterion("YEAR_OF_START <>", value, "yearOfStart");
            return (Criteria) this;
        }

        public Criteria andYearOfStartGreaterThan(Integer value) {
            addCriterion("YEAR_OF_START >", value, "yearOfStart");
            return (Criteria) this;
        }

        public Criteria andYearOfStartGreaterThanOrEqualTo(Integer value) {
            addCriterion("YEAR_OF_START >=", value, "yearOfStart");
            return (Criteria) this;
        }

        public Criteria andYearOfStartLessThan(Integer value) {
            addCriterion("YEAR_OF_START <", value, "yearOfStart");
            return (Criteria) this;
        }

        public Criteria andYearOfStartLessThanOrEqualTo(Integer value) {
            addCriterion("YEAR_OF_START <=", value, "yearOfStart");
            return (Criteria) this;
        }

        public Criteria andYearOfStartIn(List<Integer> values) {
            addCriterion("YEAR_OF_START in", values, "yearOfStart");
            return (Criteria) this;
        }

        public Criteria andYearOfStartNotIn(List<Integer> values) {
            addCriterion("YEAR_OF_START not in", values, "yearOfStart");
            return (Criteria) this;
        }

        public Criteria andYearOfStartBetween(Integer value1, Integer value2) {
            addCriterion("YEAR_OF_START between", value1, value2, "yearOfStart");
            return (Criteria) this;
        }

        public Criteria andYearOfStartNotBetween(Integer value1, Integer value2) {
            addCriterion("YEAR_OF_START not between", value1, value2, "yearOfStart");
            return (Criteria) this;
        }

        public Criteria andMonthOfStartIsNull() {
            addCriterion("MONTH_OF_START is null");
            return (Criteria) this;
        }

        public Criteria andMonthOfStartIsNotNull() {
            addCriterion("MONTH_OF_START is not null");
            return (Criteria) this;
        }

        public Criteria andMonthOfStartEqualTo(Integer value) {
            addCriterion("MONTH_OF_START =", value, "monthOfStart");
            return (Criteria) this;
        }

        public Criteria andMonthOfStartNotEqualTo(Integer value) {
            addCriterion("MONTH_OF_START <>", value, "monthOfStart");
            return (Criteria) this;
        }

        public Criteria andMonthOfStartGreaterThan(Integer value) {
            addCriterion("MONTH_OF_START >", value, "monthOfStart");
            return (Criteria) this;
        }

        public Criteria andMonthOfStartGreaterThanOrEqualTo(Integer value) {
            addCriterion("MONTH_OF_START >=", value, "monthOfStart");
            return (Criteria) this;
        }

        public Criteria andMonthOfStartLessThan(Integer value) {
            addCriterion("MONTH_OF_START <", value, "monthOfStart");
            return (Criteria) this;
        }

        public Criteria andMonthOfStartLessThanOrEqualTo(Integer value) {
            addCriterion("MONTH_OF_START <=", value, "monthOfStart");
            return (Criteria) this;
        }

        public Criteria andMonthOfStartIn(List<Integer> values) {
            addCriterion("MONTH_OF_START in", values, "monthOfStart");
            return (Criteria) this;
        }

        public Criteria andMonthOfStartNotIn(List<Integer> values) {
            addCriterion("MONTH_OF_START not in", values, "monthOfStart");
            return (Criteria) this;
        }

        public Criteria andMonthOfStartBetween(Integer value1, Integer value2) {
            addCriterion("MONTH_OF_START between", value1, value2, "monthOfStart");
            return (Criteria) this;
        }

        public Criteria andMonthOfStartNotBetween(Integer value1, Integer value2) {
            addCriterion("MONTH_OF_START not between", value1, value2, "monthOfStart");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table AGENTS_PAYMENT_FACT
     * @mbggenerated  Sun Aug 25 22:40:06 CST 2013
     */
    public static class Criterion {
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AGENTS_PAYMENT_FACT
     *
     * @mbggenerated do_not_delete_during_merge Sun Aug 25 22:14:03 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}