package com.youlema.sales.mapper.meta;

public class AssAgentsAccountRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASS_AGENTS_ACCOUNT_ROLE.AGENTS_ROLE_ID
     *
     * @mbggenerated Thu Aug 22 20:47:00 CST 2013
     */
    private Long agentsRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASS_AGENTS_ACCOUNT_ROLE.AGENTS_ACCOUNT_ID
     *
     * @mbggenerated Thu Aug 22 20:47:00 CST 2013
     */
    private Long agentsAccountId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASS_AGENTS_ACCOUNT_ROLE.AGENTS_ROLE_ID
     *
     * @return the value of ASS_AGENTS_ACCOUNT_ROLE.AGENTS_ROLE_ID
     *
     * @mbggenerated Thu Aug 22 20:47:00 CST 2013
     */
    public Long getAgentsRoleId() {
        return agentsRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASS_AGENTS_ACCOUNT_ROLE.AGENTS_ROLE_ID
     *
     * @param agentsRoleId the value for ASS_AGENTS_ACCOUNT_ROLE.AGENTS_ROLE_ID
     *
     * @mbggenerated Thu Aug 22 20:47:00 CST 2013
     */
    public void setAgentsRoleId(Long agentsRoleId) {
        this.agentsRoleId = agentsRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASS_AGENTS_ACCOUNT_ROLE.AGENTS_ACCOUNT_ID
     *
     * @return the value of ASS_AGENTS_ACCOUNT_ROLE.AGENTS_ACCOUNT_ID
     *
     * @mbggenerated Thu Aug 22 20:47:00 CST 2013
     */
    public Long getAgentsAccountId() {
        return agentsAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASS_AGENTS_ACCOUNT_ROLE.AGENTS_ACCOUNT_ID
     *
     * @param agentsAccountId the value for ASS_AGENTS_ACCOUNT_ROLE.AGENTS_ACCOUNT_ID
     *
     * @mbggenerated Thu Aug 22 20:47:00 CST 2013
     */
    public void setAgentsAccountId(Long agentsAccountId) {
        this.agentsAccountId = agentsAccountId;
    }
}