package com.youlema.sales.mapper.meta;

import java.util.Date;

public class ProductType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_TYPE.PRODUCT_TYPE_ID
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    private Long productTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_TYPE.PARENT_ID
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_TYPE.PRODUCT_TYPE_NAME
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    private String productTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_TYPE.PRODUCT_TYPE_ORD
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    private Integer productTypeOrd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_TYPE.CREATOR
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_TYPE.GMT_CREATE
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_TYPE.MODIFIER
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_TYPE.GMT_MODIFY
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    private Date gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_TYPE.IS_ENABLE
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    private Boolean isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_TYPE.PRODUCT_TYPE_CITY
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    private String productTypeCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_TYPE.TYPE_CODE
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    private String typeCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_TYPE.PRODUCT_TYPE_ID
     *
     * @return the value of PRODUCT_TYPE.PRODUCT_TYPE_ID
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    public Long getProductTypeId() {
        return productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_TYPE.PRODUCT_TYPE_ID
     *
     * @param productTypeId the value for PRODUCT_TYPE.PRODUCT_TYPE_ID
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    public void setProductTypeId(Long productTypeId) {
        this.productTypeId = productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_TYPE.PARENT_ID
     *
     * @return the value of PRODUCT_TYPE.PARENT_ID
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_TYPE.PARENT_ID
     *
     * @param parentId the value for PRODUCT_TYPE.PARENT_ID
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_TYPE.PRODUCT_TYPE_NAME
     *
     * @return the value of PRODUCT_TYPE.PRODUCT_TYPE_NAME
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    public String getProductTypeName() {
        return productTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_TYPE.PRODUCT_TYPE_NAME
     *
     * @param productTypeName the value for PRODUCT_TYPE.PRODUCT_TYPE_NAME
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    public void setProductTypeName(String productTypeName) {
        this.productTypeName = productTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_TYPE.PRODUCT_TYPE_ORD
     *
     * @return the value of PRODUCT_TYPE.PRODUCT_TYPE_ORD
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    public Integer getProductTypeOrd() {
        return productTypeOrd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_TYPE.PRODUCT_TYPE_ORD
     *
     * @param productTypeOrd the value for PRODUCT_TYPE.PRODUCT_TYPE_ORD
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    public void setProductTypeOrd(Integer productTypeOrd) {
        this.productTypeOrd = productTypeOrd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_TYPE.CREATOR
     *
     * @return the value of PRODUCT_TYPE.CREATOR
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_TYPE.CREATOR
     *
     * @param creator the value for PRODUCT_TYPE.CREATOR
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_TYPE.GMT_CREATE
     *
     * @return the value of PRODUCT_TYPE.GMT_CREATE
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_TYPE.GMT_CREATE
     *
     * @param gmtCreate the value for PRODUCT_TYPE.GMT_CREATE
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_TYPE.MODIFIER
     *
     * @return the value of PRODUCT_TYPE.MODIFIER
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_TYPE.MODIFIER
     *
     * @param modifier the value for PRODUCT_TYPE.MODIFIER
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_TYPE.GMT_MODIFY
     *
     * @return the value of PRODUCT_TYPE.GMT_MODIFY
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_TYPE.GMT_MODIFY
     *
     * @param gmtModify the value for PRODUCT_TYPE.GMT_MODIFY
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_TYPE.IS_ENABLE
     *
     * @return the value of PRODUCT_TYPE.IS_ENABLE
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_TYPE.IS_ENABLE
     *
     * @param isEnable the value for PRODUCT_TYPE.IS_ENABLE
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_TYPE.PRODUCT_TYPE_CITY
     *
     * @return the value of PRODUCT_TYPE.PRODUCT_TYPE_CITY
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    public String getProductTypeCity() {
        return productTypeCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_TYPE.PRODUCT_TYPE_CITY
     *
     * @param productTypeCity the value for PRODUCT_TYPE.PRODUCT_TYPE_CITY
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    public void setProductTypeCity(String productTypeCity) {
        this.productTypeCity = productTypeCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_TYPE.TYPE_CODE
     *
     * @return the value of PRODUCT_TYPE.TYPE_CODE
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_TYPE.TYPE_CODE
     *
     * @param typeCode the value for PRODUCT_TYPE.TYPE_CODE
     *
     * @mbggenerated Fri Aug 09 16:31:25 CST 2013
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }
}