package com.youlema.sales.mapper.meta;

public class ShortcutMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shortcut_Menu.shortcut_Menu_Id
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    private Long shortcutMenuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shortcut_Menu.agents_Account_Id
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    private Long agentsAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shortcut_Menu.agents_Menu_Id
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    private Long agentsMenuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shortcut_Menu.is_Enable
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    private Short isEnable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shortcut_Menu.shortcut_Menu_Id
     *
     * @return the value of Shortcut_Menu.shortcut_Menu_Id
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public Long getShortcutMenuId() {
        return shortcutMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shortcut_Menu.shortcut_Menu_Id
     *
     * @param shortcutMenuId the value for Shortcut_Menu.shortcut_Menu_Id
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public void setShortcutMenuId(Long shortcutMenuId) {
        this.shortcutMenuId = shortcutMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shortcut_Menu.agents_Account_Id
     *
     * @return the value of Shortcut_Menu.agents_Account_Id
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public Long getAgentsAccountId() {
        return agentsAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shortcut_Menu.agents_Account_Id
     *
     * @param agentsAccountId the value for Shortcut_Menu.agents_Account_Id
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public void setAgentsAccountId(Long agentsAccountId) {
        this.agentsAccountId = agentsAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shortcut_Menu.agents_Menu_Id
     *
     * @return the value of Shortcut_Menu.agents_Menu_Id
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public Long getAgentsMenuId() {
        return agentsMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shortcut_Menu.agents_Menu_Id
     *
     * @param agentsMenuId the value for Shortcut_Menu.agents_Menu_Id
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public void setAgentsMenuId(Long agentsMenuId) {
        this.agentsMenuId = agentsMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shortcut_Menu.is_Enable
     *
     * @return the value of Shortcut_Menu.is_Enable
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public Short getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shortcut_Menu.is_Enable
     *
     * @param isEnable the value for Shortcut_Menu.is_Enable
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public void setIsEnable(Short isEnable) {
        this.isEnable = isEnable;
    }
}