package com.youlema.sales.mapper.meta;

import java.util.ArrayList;
import java.util.List;

public class ShortcutMenuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Shortcut_Menu
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Shortcut_Menu
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Shortcut_Menu
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shortcut_Menu
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public ShortcutMenuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shortcut_Menu
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shortcut_Menu
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shortcut_Menu
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shortcut_Menu
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shortcut_Menu
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shortcut_Menu
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shortcut_Menu
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shortcut_Menu
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shortcut_Menu
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shortcut_Menu
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Shortcut_Menu
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andShortcutMenuIdIsNull() {
            addCriterion("shortcut_Menu_Id is null");
            return (Criteria) this;
        }

        public Criteria andShortcutMenuIdIsNotNull() {
            addCriterion("shortcut_Menu_Id is not null");
            return (Criteria) this;
        }

        public Criteria andShortcutMenuIdEqualTo(Long value) {
            addCriterion("shortcut_Menu_Id =", value, "shortcutMenuId");
            return (Criteria) this;
        }

        public Criteria andShortcutMenuIdNotEqualTo(Long value) {
            addCriterion("shortcut_Menu_Id <>", value, "shortcutMenuId");
            return (Criteria) this;
        }

        public Criteria andShortcutMenuIdGreaterThan(Long value) {
            addCriterion("shortcut_Menu_Id >", value, "shortcutMenuId");
            return (Criteria) this;
        }

        public Criteria andShortcutMenuIdGreaterThanOrEqualTo(Long value) {
            addCriterion("shortcut_Menu_Id >=", value, "shortcutMenuId");
            return (Criteria) this;
        }

        public Criteria andShortcutMenuIdLessThan(Long value) {
            addCriterion("shortcut_Menu_Id <", value, "shortcutMenuId");
            return (Criteria) this;
        }

        public Criteria andShortcutMenuIdLessThanOrEqualTo(Long value) {
            addCriterion("shortcut_Menu_Id <=", value, "shortcutMenuId");
            return (Criteria) this;
        }

        public Criteria andShortcutMenuIdIn(List<Long> values) {
            addCriterion("shortcut_Menu_Id in", values, "shortcutMenuId");
            return (Criteria) this;
        }

        public Criteria andShortcutMenuIdNotIn(List<Long> values) {
            addCriterion("shortcut_Menu_Id not in", values, "shortcutMenuId");
            return (Criteria) this;
        }

        public Criteria andShortcutMenuIdBetween(Long value1, Long value2) {
            addCriterion("shortcut_Menu_Id between", value1, value2, "shortcutMenuId");
            return (Criteria) this;
        }

        public Criteria andShortcutMenuIdNotBetween(Long value1, Long value2) {
            addCriterion("shortcut_Menu_Id not between", value1, value2, "shortcutMenuId");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdIsNull() {
            addCriterion("agents_Account_Id is null");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdIsNotNull() {
            addCriterion("agents_Account_Id is not null");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdEqualTo(Long value) {
            addCriterion("agents_Account_Id =", value, "agentsAccountId");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdNotEqualTo(Long value) {
            addCriterion("agents_Account_Id <>", value, "agentsAccountId");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdGreaterThan(Long value) {
            addCriterion("agents_Account_Id >", value, "agentsAccountId");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdGreaterThanOrEqualTo(Long value) {
            addCriterion("agents_Account_Id >=", value, "agentsAccountId");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdLessThan(Long value) {
            addCriterion("agents_Account_Id <", value, "agentsAccountId");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdLessThanOrEqualTo(Long value) {
            addCriterion("agents_Account_Id <=", value, "agentsAccountId");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdIn(List<Long> values) {
            addCriterion("agents_Account_Id in", values, "agentsAccountId");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdNotIn(List<Long> values) {
            addCriterion("agents_Account_Id not in", values, "agentsAccountId");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdBetween(Long value1, Long value2) {
            addCriterion("agents_Account_Id between", value1, value2, "agentsAccountId");
            return (Criteria) this;
        }

        public Criteria andAgentsAccountIdNotBetween(Long value1, Long value2) {
            addCriterion("agents_Account_Id not between", value1, value2, "agentsAccountId");
            return (Criteria) this;
        }

        public Criteria andAgentsMenuIdIsNull() {
            addCriterion("agents_Menu_Id is null");
            return (Criteria) this;
        }

        public Criteria andAgentsMenuIdIsNotNull() {
            addCriterion("agents_Menu_Id is not null");
            return (Criteria) this;
        }

        public Criteria andAgentsMenuIdEqualTo(Long value) {
            addCriterion("agents_Menu_Id =", value, "agentsMenuId");
            return (Criteria) this;
        }

        public Criteria andAgentsMenuIdNotEqualTo(Long value) {
            addCriterion("agents_Menu_Id <>", value, "agentsMenuId");
            return (Criteria) this;
        }

        public Criteria andAgentsMenuIdGreaterThan(Long value) {
            addCriterion("agents_Menu_Id >", value, "agentsMenuId");
            return (Criteria) this;
        }

        public Criteria andAgentsMenuIdGreaterThanOrEqualTo(Long value) {
            addCriterion("agents_Menu_Id >=", value, "agentsMenuId");
            return (Criteria) this;
        }

        public Criteria andAgentsMenuIdLessThan(Long value) {
            addCriterion("agents_Menu_Id <", value, "agentsMenuId");
            return (Criteria) this;
        }

        public Criteria andAgentsMenuIdLessThanOrEqualTo(Long value) {
            addCriterion("agents_Menu_Id <=", value, "agentsMenuId");
            return (Criteria) this;
        }

        public Criteria andAgentsMenuIdIn(List<Long> values) {
            addCriterion("agents_Menu_Id in", values, "agentsMenuId");
            return (Criteria) this;
        }

        public Criteria andAgentsMenuIdNotIn(List<Long> values) {
            addCriterion("agents_Menu_Id not in", values, "agentsMenuId");
            return (Criteria) this;
        }

        public Criteria andAgentsMenuIdBetween(Long value1, Long value2) {
            addCriterion("agents_Menu_Id between", value1, value2, "agentsMenuId");
            return (Criteria) this;
        }

        public Criteria andAgentsMenuIdNotBetween(Long value1, Long value2) {
            addCriterion("agents_Menu_Id not between", value1, value2, "agentsMenuId");
            return (Criteria) this;
        }

        public Criteria andIsEnableIsNull() {
            addCriterion("is_Enable is null");
            return (Criteria) this;
        }

        public Criteria andIsEnableIsNotNull() {
            addCriterion("is_Enable is not null");
            return (Criteria) this;
        }

        public Criteria andIsEnableEqualTo(Short value) {
            addCriterion("is_Enable =", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableNotEqualTo(Short value) {
            addCriterion("is_Enable <>", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableGreaterThan(Short value) {
            addCriterion("is_Enable >", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableGreaterThanOrEqualTo(Short value) {
            addCriterion("is_Enable >=", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableLessThan(Short value) {
            addCriterion("is_Enable <", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableLessThanOrEqualTo(Short value) {
            addCriterion("is_Enable <=", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableIn(List<Short> values) {
            addCriterion("is_Enable in", values, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableNotIn(List<Short> values) {
            addCriterion("is_Enable not in", values, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableBetween(Short value1, Short value2) {
            addCriterion("is_Enable between", value1, value2, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableNotBetween(Short value1, Short value2) {
            addCriterion("is_Enable not between", value1, value2, "isEnable");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Shortcut_Menu
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 17 23:46:53 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Shortcut_Menu
     *
     * @mbggenerated Mon Jun 17 23:46:53 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}