package com.youlema.sales.mapper.meta;

import java.util.Date;

public class TourLine {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.tour_Line_Id
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private Long tourLineId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.product_Main_Type_Id
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private Long productMainTypeId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.product_Minor_Type_Id
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private Long productMinorTypeId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.line_Code
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private String lineCode;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.line_Name
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private String lineName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.line_Topic
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private String lineTopic;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.line_Type
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private String lineType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.line_Brand
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private String lineBrand;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.tour_Cards
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private String tourCards;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.before_Days_Grant_Vista
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private Integer beforeDaysGrantVista;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.days_Night
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private Integer daysNight;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.days_During
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private Integer daysDuring;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.leave_City
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private String leaveCity;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.leave_City_Traffic
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private String leaveCityTraffic;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.return_City
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private String returnCity;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.return_City_Traffic
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private String returnCityTraffic;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.through_Citys
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private String throughCitys;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.tour_Attractions
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private String tourAttractions;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.key_Words
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private String keyWords;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.design_Status
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private String designStatus;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.gmt_Desing_Complete
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private Date gmtDesingComplete;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.is_Enable
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private Short isEnable;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.gmt_Create
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private Date gmtCreate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.creator
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private String creator;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.gmt_Modify
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private Date gmtModify;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.modifier
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private String modifier;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.memo
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private String memo;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.audit_Opinion
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private String auditOpinion;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.audit_Status
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private String auditStatus;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.target_Customers
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private String targetCustomers;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.tour_Purpose
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private String tourPurpose;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.is_Deleted
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private Short isDeleted;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.PV
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private Long pv;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.applicable_Type
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private String applicableType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column Tour_Line.tour_Highlights
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    private String tourHighlights;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.tour_Line_Id
     * @return  the value of Tour_Line.tour_Line_Id
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public Long getTourLineId() {
        return tourLineId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.tour_Line_Id
     * @param tourLineId  the value for Tour_Line.tour_Line_Id
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setTourLineId(Long tourLineId) {
        this.tourLineId = tourLineId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.product_Main_Type_Id
     * @return  the value of Tour_Line.product_Main_Type_Id
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public Long getProductMainTypeId() {
        return productMainTypeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.product_Main_Type_Id
     * @param productMainTypeId  the value for Tour_Line.product_Main_Type_Id
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setProductMainTypeId(Long productMainTypeId) {
        this.productMainTypeId = productMainTypeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.product_Minor_Type_Id
     * @return  the value of Tour_Line.product_Minor_Type_Id
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public Long getProductMinorTypeId() {
        return productMinorTypeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.product_Minor_Type_Id
     * @param productMinorTypeId  the value for Tour_Line.product_Minor_Type_Id
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setProductMinorTypeId(Long productMinorTypeId) {
        this.productMinorTypeId = productMinorTypeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.line_Code
     * @return  the value of Tour_Line.line_Code
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public String getLineCode() {
        return lineCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.line_Code
     * @param lineCode  the value for Tour_Line.line_Code
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setLineCode(String lineCode) {
        this.lineCode = lineCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.line_Name
     * @return  the value of Tour_Line.line_Name
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public String getLineName() {
        return lineName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.line_Name
     * @param lineName  the value for Tour_Line.line_Name
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setLineName(String lineName) {
        this.lineName = lineName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.line_Topic
     * @return  the value of Tour_Line.line_Topic
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public String getLineTopic() {
        return lineTopic;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.line_Topic
     * @param lineTopic  the value for Tour_Line.line_Topic
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setLineTopic(String lineTopic) {
        this.lineTopic = lineTopic;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.line_Type
     * @return  the value of Tour_Line.line_Type
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public String getLineType() {
        return lineType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.line_Type
     * @param lineType  the value for Tour_Line.line_Type
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setLineType(String lineType) {
        this.lineType = lineType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.line_Brand
     * @return  the value of Tour_Line.line_Brand
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public String getLineBrand() {
        return lineBrand;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.line_Brand
     * @param lineBrand  the value for Tour_Line.line_Brand
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setLineBrand(String lineBrand) {
        this.lineBrand = lineBrand;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.tour_Cards
     * @return  the value of Tour_Line.tour_Cards
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public String getTourCards() {
        return tourCards;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.tour_Cards
     * @param tourCards  the value for Tour_Line.tour_Cards
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setTourCards(String tourCards) {
        this.tourCards = tourCards;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.before_Days_Grant_Vista
     * @return  the value of Tour_Line.before_Days_Grant_Vista
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public Integer getBeforeDaysGrantVista() {
        return beforeDaysGrantVista;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.before_Days_Grant_Vista
     * @param beforeDaysGrantVista  the value for Tour_Line.before_Days_Grant_Vista
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setBeforeDaysGrantVista(Integer beforeDaysGrantVista) {
        this.beforeDaysGrantVista = beforeDaysGrantVista;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.days_Night
     * @return  the value of Tour_Line.days_Night
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public Integer getDaysNight() {
        return daysNight;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.days_Night
     * @param daysNight  the value for Tour_Line.days_Night
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setDaysNight(Integer daysNight) {
        this.daysNight = daysNight;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.days_During
     * @return  the value of Tour_Line.days_During
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public Integer getDaysDuring() {
        return daysDuring;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.days_During
     * @param daysDuring  the value for Tour_Line.days_During
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setDaysDuring(Integer daysDuring) {
        this.daysDuring = daysDuring;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.leave_City
     * @return  the value of Tour_Line.leave_City
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public String getLeaveCity() {
        return leaveCity;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.leave_City
     * @param leaveCity  the value for Tour_Line.leave_City
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setLeaveCity(String leaveCity) {
        this.leaveCity = leaveCity;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.leave_City_Traffic
     * @return  the value of Tour_Line.leave_City_Traffic
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public String getLeaveCityTraffic() {
        return leaveCityTraffic;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.leave_City_Traffic
     * @param leaveCityTraffic  the value for Tour_Line.leave_City_Traffic
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setLeaveCityTraffic(String leaveCityTraffic) {
        this.leaveCityTraffic = leaveCityTraffic;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.return_City
     * @return  the value of Tour_Line.return_City
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public String getReturnCity() {
        return returnCity;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.return_City
     * @param returnCity  the value for Tour_Line.return_City
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setReturnCity(String returnCity) {
        this.returnCity = returnCity;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.return_City_Traffic
     * @return  the value of Tour_Line.return_City_Traffic
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public String getReturnCityTraffic() {
        return returnCityTraffic;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.return_City_Traffic
     * @param returnCityTraffic  the value for Tour_Line.return_City_Traffic
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setReturnCityTraffic(String returnCityTraffic) {
        this.returnCityTraffic = returnCityTraffic;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.through_Citys
     * @return  the value of Tour_Line.through_Citys
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public String getThroughCitys() {
        return throughCitys;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.through_Citys
     * @param throughCitys  the value for Tour_Line.through_Citys
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setThroughCitys(String throughCitys) {
        this.throughCitys = throughCitys;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.tour_Attractions
     * @return  the value of Tour_Line.tour_Attractions
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public String getTourAttractions() {
        return tourAttractions;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.tour_Attractions
     * @param tourAttractions  the value for Tour_Line.tour_Attractions
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setTourAttractions(String tourAttractions) {
        this.tourAttractions = tourAttractions;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.key_Words
     * @return  the value of Tour_Line.key_Words
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public String getKeyWords() {
        return keyWords;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.key_Words
     * @param keyWords  the value for Tour_Line.key_Words
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setKeyWords(String keyWords) {
        this.keyWords = keyWords;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.design_Status
     * @return  the value of Tour_Line.design_Status
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public String getDesignStatus() {
        return designStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.design_Status
     * @param designStatus  the value for Tour_Line.design_Status
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setDesignStatus(String designStatus) {
        this.designStatus = designStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.gmt_Desing_Complete
     * @return  the value of Tour_Line.gmt_Desing_Complete
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public Date getGmtDesingComplete() {
        return gmtDesingComplete;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.gmt_Desing_Complete
     * @param gmtDesingComplete  the value for Tour_Line.gmt_Desing_Complete
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setGmtDesingComplete(Date gmtDesingComplete) {
        this.gmtDesingComplete = gmtDesingComplete;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.is_Enable
     * @return  the value of Tour_Line.is_Enable
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public Short getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.is_Enable
     * @param isEnable  the value for Tour_Line.is_Enable
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setIsEnable(Short isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.gmt_Create
     * @return  the value of Tour_Line.gmt_Create
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.gmt_Create
     * @param gmtCreate  the value for Tour_Line.gmt_Create
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.creator
     * @return  the value of Tour_Line.creator
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.creator
     * @param creator  the value for Tour_Line.creator
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.gmt_Modify
     * @return  the value of Tour_Line.gmt_Modify
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.gmt_Modify
     * @param gmtModify  the value for Tour_Line.gmt_Modify
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.modifier
     * @return  the value of Tour_Line.modifier
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.modifier
     * @param modifier  the value for Tour_Line.modifier
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.memo
     * @return  the value of Tour_Line.memo
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.memo
     * @param memo  the value for Tour_Line.memo
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.audit_Opinion
     * @return  the value of Tour_Line.audit_Opinion
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public String getAuditOpinion() {
        return auditOpinion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.audit_Opinion
     * @param auditOpinion  the value for Tour_Line.audit_Opinion
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setAuditOpinion(String auditOpinion) {
        this.auditOpinion = auditOpinion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.audit_Status
     * @return  the value of Tour_Line.audit_Status
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.audit_Status
     * @param auditStatus  the value for Tour_Line.audit_Status
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.target_Customers
     * @return  the value of Tour_Line.target_Customers
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public String getTargetCustomers() {
        return targetCustomers;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.target_Customers
     * @param targetCustomers  the value for Tour_Line.target_Customers
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setTargetCustomers(String targetCustomers) {
        this.targetCustomers = targetCustomers;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.tour_Purpose
     * @return  the value of Tour_Line.tour_Purpose
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public String getTourPurpose() {
        return tourPurpose;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.tour_Purpose
     * @param tourPurpose  the value for Tour_Line.tour_Purpose
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setTourPurpose(String tourPurpose) {
        this.tourPurpose = tourPurpose;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.is_Deleted
     * @return  the value of Tour_Line.is_Deleted
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public Short getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.is_Deleted
     * @param isDeleted  the value for Tour_Line.is_Deleted
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setIsDeleted(Short isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.PV
     * @return  the value of Tour_Line.PV
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public Long getPv() {
        return pv;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.PV
     * @param pv  the value for Tour_Line.PV
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setPv(Long pv) {
        this.pv = pv;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.applicable_Type
     * @return  the value of Tour_Line.applicable_Type
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public String getApplicableType() {
        return applicableType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.applicable_Type
     * @param applicableType  the value for Tour_Line.applicable_Type
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setApplicableType(String applicableType) {
        this.applicableType = applicableType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column Tour_Line.tour_Highlights
     * @return  the value of Tour_Line.tour_Highlights
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public String getTourHighlights() {
        return tourHighlights;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column Tour_Line.tour_Highlights
     * @param tourHighlights  the value for Tour_Line.tour_Highlights
     * @mbggenerated  Wed Jun 19 20:58:41 CST 2013
     */
    public void setTourHighlights(String tourHighlights) {
        this.tourHighlights = tourHighlights;
    }
}