package com.youlema.sales.mapper.meta;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TourLineExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tour_line
	 * @mbggenerated  Tue Jun 18 19:51:47 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tour_line
	 * @mbggenerated  Tue Jun 18 19:51:47 CST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tour_line
	 * @mbggenerated  Tue Jun 18 19:51:47 CST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tour_line
	 * @mbggenerated  Tue Jun 18 19:51:47 CST 2013
	 */
	public TourLineExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tour_line
	 * @mbggenerated  Tue Jun 18 19:51:47 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tour_line
	 * @mbggenerated  Tue Jun 18 19:51:47 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tour_line
	 * @mbggenerated  Tue Jun 18 19:51:47 CST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tour_line
	 * @mbggenerated  Tue Jun 18 19:51:47 CST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tour_line
	 * @mbggenerated  Tue Jun 18 19:51:47 CST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tour_line
	 * @mbggenerated  Tue Jun 18 19:51:47 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tour_line
	 * @mbggenerated  Tue Jun 18 19:51:47 CST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tour_line
	 * @mbggenerated  Tue Jun 18 19:51:47 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tour_line
	 * @mbggenerated  Tue Jun 18 19:51:47 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tour_line
	 * @mbggenerated  Tue Jun 18 19:51:47 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tour_line
	 * @mbggenerated  Tue Jun 18 19:51:47 CST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andTourLineIdIsNull() {
			addCriterion("tour_Line_Id is null");
			return (Criteria) this;
		}

		public Criteria andTourLineIdIsNotNull() {
			addCriterion("tour_Line_Id is not null");
			return (Criteria) this;
		}

		public Criteria andTourLineIdEqualTo(Long value) {
			addCriterion("tour_Line_Id =", value, "tourLineId");
			return (Criteria) this;
		}

		public Criteria andTourLineIdNotEqualTo(Long value) {
			addCriterion("tour_Line_Id <>", value, "tourLineId");
			return (Criteria) this;
		}

		public Criteria andTourLineIdGreaterThan(Long value) {
			addCriterion("tour_Line_Id >", value, "tourLineId");
			return (Criteria) this;
		}

		public Criteria andTourLineIdGreaterThanOrEqualTo(Long value) {
			addCriterion("tour_Line_Id >=", value, "tourLineId");
			return (Criteria) this;
		}

		public Criteria andTourLineIdLessThan(Long value) {
			addCriterion("tour_Line_Id <", value, "tourLineId");
			return (Criteria) this;
		}

		public Criteria andTourLineIdLessThanOrEqualTo(Long value) {
			addCriterion("tour_Line_Id <=", value, "tourLineId");
			return (Criteria) this;
		}

		public Criteria andTourLineIdIn(List<Long> values) {
			addCriterion("tour_Line_Id in", values, "tourLineId");
			return (Criteria) this;
		}

		public Criteria andTourLineIdNotIn(List<Long> values) {
			addCriterion("tour_Line_Id not in", values, "tourLineId");
			return (Criteria) this;
		}

		public Criteria andTourLineIdBetween(Long value1, Long value2) {
			addCriterion("tour_Line_Id between", value1, value2, "tourLineId");
			return (Criteria) this;
		}

		public Criteria andTourLineIdNotBetween(Long value1, Long value2) {
			addCriterion("tour_Line_Id not between", value1, value2,
					"tourLineId");
			return (Criteria) this;
		}

		public Criteria andProductTypeIdIsNull() {
			addCriterion("product_Type_Id is null");
			return (Criteria) this;
		}

		public Criteria andProductTypeIdIsNotNull() {
			addCriterion("product_Type_Id is not null");
			return (Criteria) this;
		}

		public Criteria andProductTypeIdEqualTo(Long value) {
			addCriterion("product_Type_Id =", value, "productTypeId");
			return (Criteria) this;
		}

		public Criteria andProductTypeIdNotEqualTo(Long value) {
			addCriterion("product_Type_Id <>", value, "productTypeId");
			return (Criteria) this;
		}

		public Criteria andProductTypeIdGreaterThan(Long value) {
			addCriterion("product_Type_Id >", value, "productTypeId");
			return (Criteria) this;
		}

		public Criteria andProductTypeIdGreaterThanOrEqualTo(Long value) {
			addCriterion("product_Type_Id >=", value, "productTypeId");
			return (Criteria) this;
		}

		public Criteria andProductTypeIdLessThan(Long value) {
			addCriterion("product_Type_Id <", value, "productTypeId");
			return (Criteria) this;
		}

		public Criteria andProductTypeIdLessThanOrEqualTo(Long value) {
			addCriterion("product_Type_Id <=", value, "productTypeId");
			return (Criteria) this;
		}

		public Criteria andProductTypeIdIn(List<Long> values) {
			addCriterion("product_Type_Id in", values, "productTypeId");
			return (Criteria) this;
		}

		public Criteria andProductTypeIdNotIn(List<Long> values) {
			addCriterion("product_Type_Id not in", values, "productTypeId");
			return (Criteria) this;
		}

		public Criteria andProductTypeIdBetween(Long value1, Long value2) {
			addCriterion("product_Type_Id between", value1, value2,
					"productTypeId");
			return (Criteria) this;
		}

		public Criteria andProductTypeIdNotBetween(Long value1, Long value2) {
			addCriterion("product_Type_Id not between", value1, value2,
					"productTypeId");
			return (Criteria) this;
		}

		public Criteria andProProductTypeIdIsNull() {
			addCriterion("Pro_product_Type_Id is null");
			return (Criteria) this;
		}

		public Criteria andProProductTypeIdIsNotNull() {
			addCriterion("Pro_product_Type_Id is not null");
			return (Criteria) this;
		}

		public Criteria andProProductTypeIdEqualTo(Long value) {
			addCriterion("Pro_product_Type_Id =", value, "proProductTypeId");
			return (Criteria) this;
		}

		public Criteria andProProductTypeIdNotEqualTo(Long value) {
			addCriterion("Pro_product_Type_Id <>", value, "proProductTypeId");
			return (Criteria) this;
		}

		public Criteria andProProductTypeIdGreaterThan(Long value) {
			addCriterion("Pro_product_Type_Id >", value, "proProductTypeId");
			return (Criteria) this;
		}

		public Criteria andProProductTypeIdGreaterThanOrEqualTo(Long value) {
			addCriterion("Pro_product_Type_Id >=", value, "proProductTypeId");
			return (Criteria) this;
		}

		public Criteria andProProductTypeIdLessThan(Long value) {
			addCriterion("Pro_product_Type_Id <", value, "proProductTypeId");
			return (Criteria) this;
		}

		public Criteria andProProductTypeIdLessThanOrEqualTo(Long value) {
			addCriterion("Pro_product_Type_Id <=", value, "proProductTypeId");
			return (Criteria) this;
		}

		public Criteria andProProductTypeIdIn(List<Long> values) {
			addCriterion("Pro_product_Type_Id in", values, "proProductTypeId");
			return (Criteria) this;
		}

		public Criteria andProProductTypeIdNotIn(List<Long> values) {
			addCriterion("Pro_product_Type_Id not in", values,
					"proProductTypeId");
			return (Criteria) this;
		}

		public Criteria andProProductTypeIdBetween(Long value1, Long value2) {
			addCriterion("Pro_product_Type_Id between", value1, value2,
					"proProductTypeId");
			return (Criteria) this;
		}

		public Criteria andProProductTypeIdNotBetween(Long value1, Long value2) {
			addCriterion("Pro_product_Type_Id not between", value1, value2,
					"proProductTypeId");
			return (Criteria) this;
		}

		public Criteria andLineCodeIsNull() {
			addCriterion("line_Code is null");
			return (Criteria) this;
		}

		public Criteria andLineCodeIsNotNull() {
			addCriterion("line_Code is not null");
			return (Criteria) this;
		}

		public Criteria andLineCodeEqualTo(String value) {
			addCriterion("line_Code =", value, "lineCode");
			return (Criteria) this;
		}

		public Criteria andLineCodeNotEqualTo(String value) {
			addCriterion("line_Code <>", value, "lineCode");
			return (Criteria) this;
		}

		public Criteria andLineCodeGreaterThan(String value) {
			addCriterion("line_Code >", value, "lineCode");
			return (Criteria) this;
		}

		public Criteria andLineCodeGreaterThanOrEqualTo(String value) {
			addCriterion("line_Code >=", value, "lineCode");
			return (Criteria) this;
		}

		public Criteria andLineCodeLessThan(String value) {
			addCriterion("line_Code <", value, "lineCode");
			return (Criteria) this;
		}

		public Criteria andLineCodeLessThanOrEqualTo(String value) {
			addCriterion("line_Code <=", value, "lineCode");
			return (Criteria) this;
		}

		public Criteria andLineCodeLike(String value) {
			addCriterion("line_Code like", value, "lineCode");
			return (Criteria) this;
		}

		public Criteria andLineCodeNotLike(String value) {
			addCriterion("line_Code not like", value, "lineCode");
			return (Criteria) this;
		}

		public Criteria andLineCodeIn(List<String> values) {
			addCriterion("line_Code in", values, "lineCode");
			return (Criteria) this;
		}

		public Criteria andLineCodeNotIn(List<String> values) {
			addCriterion("line_Code not in", values, "lineCode");
			return (Criteria) this;
		}

		public Criteria andLineCodeBetween(String value1, String value2) {
			addCriterion("line_Code between", value1, value2, "lineCode");
			return (Criteria) this;
		}

		public Criteria andLineCodeNotBetween(String value1, String value2) {
			addCriterion("line_Code not between", value1, value2, "lineCode");
			return (Criteria) this;
		}

		public Criteria andLineNameIsNull() {
			addCriterion("line_Name is null");
			return (Criteria) this;
		}

		public Criteria andLineNameIsNotNull() {
			addCriterion("line_Name is not null");
			return (Criteria) this;
		}

		public Criteria andLineNameEqualTo(String value) {
			addCriterion("line_Name =", value, "lineName");
			return (Criteria) this;
		}

		public Criteria andLineNameNotEqualTo(String value) {
			addCriterion("line_Name <>", value, "lineName");
			return (Criteria) this;
		}

		public Criteria andLineNameGreaterThan(String value) {
			addCriterion("line_Name >", value, "lineName");
			return (Criteria) this;
		}

		public Criteria andLineNameGreaterThanOrEqualTo(String value) {
			addCriterion("line_Name >=", value, "lineName");
			return (Criteria) this;
		}

		public Criteria andLineNameLessThan(String value) {
			addCriterion("line_Name <", value, "lineName");
			return (Criteria) this;
		}

		public Criteria andLineNameLessThanOrEqualTo(String value) {
			addCriterion("line_Name <=", value, "lineName");
			return (Criteria) this;
		}

		public Criteria andLineNameLike(String value) {
			addCriterion("line_Name like", value, "lineName");
			return (Criteria) this;
		}

		public Criteria andLineNameNotLike(String value) {
			addCriterion("line_Name not like", value, "lineName");
			return (Criteria) this;
		}

		public Criteria andLineNameIn(List<String> values) {
			addCriterion("line_Name in", values, "lineName");
			return (Criteria) this;
		}

		public Criteria andLineNameNotIn(List<String> values) {
			addCriterion("line_Name not in", values, "lineName");
			return (Criteria) this;
		}

		public Criteria andLineNameBetween(String value1, String value2) {
			addCriterion("line_Name between", value1, value2, "lineName");
			return (Criteria) this;
		}

		public Criteria andLineNameNotBetween(String value1, String value2) {
			addCriterion("line_Name not between", value1, value2, "lineName");
			return (Criteria) this;
		}

		public Criteria andLineTopicIsNull() {
			addCriterion("line_Topic is null");
			return (Criteria) this;
		}

		public Criteria andLineTopicIsNotNull() {
			addCriterion("line_Topic is not null");
			return (Criteria) this;
		}

		public Criteria andLineTopicEqualTo(String value) {
			addCriterion("line_Topic =", value, "lineTopic");
			return (Criteria) this;
		}

		public Criteria andLineTopicNotEqualTo(String value) {
			addCriterion("line_Topic <>", value, "lineTopic");
			return (Criteria) this;
		}

		public Criteria andLineTopicGreaterThan(String value) {
			addCriterion("line_Topic >", value, "lineTopic");
			return (Criteria) this;
		}

		public Criteria andLineTopicGreaterThanOrEqualTo(String value) {
			addCriterion("line_Topic >=", value, "lineTopic");
			return (Criteria) this;
		}

		public Criteria andLineTopicLessThan(String value) {
			addCriterion("line_Topic <", value, "lineTopic");
			return (Criteria) this;
		}

		public Criteria andLineTopicLessThanOrEqualTo(String value) {
			addCriterion("line_Topic <=", value, "lineTopic");
			return (Criteria) this;
		}

		public Criteria andLineTopicLike(String value) {
			addCriterion("line_Topic like", value, "lineTopic");
			return (Criteria) this;
		}

		public Criteria andLineTopicNotLike(String value) {
			addCriterion("line_Topic not like", value, "lineTopic");
			return (Criteria) this;
		}

		public Criteria andLineTopicIn(List<String> values) {
			addCriterion("line_Topic in", values, "lineTopic");
			return (Criteria) this;
		}

		public Criteria andLineTopicNotIn(List<String> values) {
			addCriterion("line_Topic not in", values, "lineTopic");
			return (Criteria) this;
		}

		public Criteria andLineTopicBetween(String value1, String value2) {
			addCriterion("line_Topic between", value1, value2, "lineTopic");
			return (Criteria) this;
		}

		public Criteria andLineTopicNotBetween(String value1, String value2) {
			addCriterion("line_Topic not between", value1, value2, "lineTopic");
			return (Criteria) this;
		}

		public Criteria andLineTypeIsNull() {
			addCriterion("line_Type is null");
			return (Criteria) this;
		}

		public Criteria andLineTypeIsNotNull() {
			addCriterion("line_Type is not null");
			return (Criteria) this;
		}

		public Criteria andLineTypeEqualTo(String value) {
			addCriterion("line_Type =", value, "lineType");
			return (Criteria) this;
		}

		public Criteria andLineTypeNotEqualTo(String value) {
			addCriterion("line_Type <>", value, "lineType");
			return (Criteria) this;
		}

		public Criteria andLineTypeGreaterThan(String value) {
			addCriterion("line_Type >", value, "lineType");
			return (Criteria) this;
		}

		public Criteria andLineTypeGreaterThanOrEqualTo(String value) {
			addCriterion("line_Type >=", value, "lineType");
			return (Criteria) this;
		}

		public Criteria andLineTypeLessThan(String value) {
			addCriterion("line_Type <", value, "lineType");
			return (Criteria) this;
		}

		public Criteria andLineTypeLessThanOrEqualTo(String value) {
			addCriterion("line_Type <=", value, "lineType");
			return (Criteria) this;
		}

		public Criteria andLineTypeLike(String value) {
			addCriterion("line_Type like", value, "lineType");
			return (Criteria) this;
		}

		public Criteria andLineTypeNotLike(String value) {
			addCriterion("line_Type not like", value, "lineType");
			return (Criteria) this;
		}

		public Criteria andLineTypeIn(List<String> values) {
			addCriterion("line_Type in", values, "lineType");
			return (Criteria) this;
		}

		public Criteria andLineTypeNotIn(List<String> values) {
			addCriterion("line_Type not in", values, "lineType");
			return (Criteria) this;
		}

		public Criteria andLineTypeBetween(String value1, String value2) {
			addCriterion("line_Type between", value1, value2, "lineType");
			return (Criteria) this;
		}

		public Criteria andLineTypeNotBetween(String value1, String value2) {
			addCriterion("line_Type not between", value1, value2, "lineType");
			return (Criteria) this;
		}

		public Criteria andLineBrandIsNull() {
			addCriterion("line_Brand is null");
			return (Criteria) this;
		}

		public Criteria andLineBrandIsNotNull() {
			addCriterion("line_Brand is not null");
			return (Criteria) this;
		}

		public Criteria andLineBrandEqualTo(String value) {
			addCriterion("line_Brand =", value, "lineBrand");
			return (Criteria) this;
		}

		public Criteria andLineBrandNotEqualTo(String value) {
			addCriterion("line_Brand <>", value, "lineBrand");
			return (Criteria) this;
		}

		public Criteria andLineBrandGreaterThan(String value) {
			addCriterion("line_Brand >", value, "lineBrand");
			return (Criteria) this;
		}

		public Criteria andLineBrandGreaterThanOrEqualTo(String value) {
			addCriterion("line_Brand >=", value, "lineBrand");
			return (Criteria) this;
		}

		public Criteria andLineBrandLessThan(String value) {
			addCriterion("line_Brand <", value, "lineBrand");
			return (Criteria) this;
		}

		public Criteria andLineBrandLessThanOrEqualTo(String value) {
			addCriterion("line_Brand <=", value, "lineBrand");
			return (Criteria) this;
		}

		public Criteria andLineBrandLike(String value) {
			addCriterion("line_Brand like", value, "lineBrand");
			return (Criteria) this;
		}

		public Criteria andLineBrandNotLike(String value) {
			addCriterion("line_Brand not like", value, "lineBrand");
			return (Criteria) this;
		}

		public Criteria andLineBrandIn(List<String> values) {
			addCriterion("line_Brand in", values, "lineBrand");
			return (Criteria) this;
		}

		public Criteria andLineBrandNotIn(List<String> values) {
			addCriterion("line_Brand not in", values, "lineBrand");
			return (Criteria) this;
		}

		public Criteria andLineBrandBetween(String value1, String value2) {
			addCriterion("line_Brand between", value1, value2, "lineBrand");
			return (Criteria) this;
		}

		public Criteria andLineBrandNotBetween(String value1, String value2) {
			addCriterion("line_Brand not between", value1, value2, "lineBrand");
			return (Criteria) this;
		}

		public Criteria andTourCardsIsNull() {
			addCriterion("tour_Cards is null");
			return (Criteria) this;
		}

		public Criteria andTourCardsIsNotNull() {
			addCriterion("tour_Cards is not null");
			return (Criteria) this;
		}

		public Criteria andTourCardsEqualTo(String value) {
			addCriterion("tour_Cards =", value, "tourCards");
			return (Criteria) this;
		}

		public Criteria andTourCardsNotEqualTo(String value) {
			addCriterion("tour_Cards <>", value, "tourCards");
			return (Criteria) this;
		}

		public Criteria andTourCardsGreaterThan(String value) {
			addCriterion("tour_Cards >", value, "tourCards");
			return (Criteria) this;
		}

		public Criteria andTourCardsGreaterThanOrEqualTo(String value) {
			addCriterion("tour_Cards >=", value, "tourCards");
			return (Criteria) this;
		}

		public Criteria andTourCardsLessThan(String value) {
			addCriterion("tour_Cards <", value, "tourCards");
			return (Criteria) this;
		}

		public Criteria andTourCardsLessThanOrEqualTo(String value) {
			addCriterion("tour_Cards <=", value, "tourCards");
			return (Criteria) this;
		}

		public Criteria andTourCardsLike(String value) {
			addCriterion("tour_Cards like", value, "tourCards");
			return (Criteria) this;
		}

		public Criteria andTourCardsNotLike(String value) {
			addCriterion("tour_Cards not like", value, "tourCards");
			return (Criteria) this;
		}

		public Criteria andTourCardsIn(List<String> values) {
			addCriterion("tour_Cards in", values, "tourCards");
			return (Criteria) this;
		}

		public Criteria andTourCardsNotIn(List<String> values) {
			addCriterion("tour_Cards not in", values, "tourCards");
			return (Criteria) this;
		}

		public Criteria andTourCardsBetween(String value1, String value2) {
			addCriterion("tour_Cards between", value1, value2, "tourCards");
			return (Criteria) this;
		}

		public Criteria andTourCardsNotBetween(String value1, String value2) {
			addCriterion("tour_Cards not between", value1, value2, "tourCards");
			return (Criteria) this;
		}

		public Criteria andBeforeDaysGrantVistaIsNull() {
			addCriterion("before_Days_Grant_Vista is null");
			return (Criteria) this;
		}

		public Criteria andBeforeDaysGrantVistaIsNotNull() {
			addCriterion("before_Days_Grant_Vista is not null");
			return (Criteria) this;
		}

		public Criteria andBeforeDaysGrantVistaEqualTo(Integer value) {
			addCriterion("before_Days_Grant_Vista =", value,
					"beforeDaysGrantVista");
			return (Criteria) this;
		}

		public Criteria andBeforeDaysGrantVistaNotEqualTo(Integer value) {
			addCriterion("before_Days_Grant_Vista <>", value,
					"beforeDaysGrantVista");
			return (Criteria) this;
		}

		public Criteria andBeforeDaysGrantVistaGreaterThan(Integer value) {
			addCriterion("before_Days_Grant_Vista >", value,
					"beforeDaysGrantVista");
			return (Criteria) this;
		}

		public Criteria andBeforeDaysGrantVistaGreaterThanOrEqualTo(
				Integer value) {
			addCriterion("before_Days_Grant_Vista >=", value,
					"beforeDaysGrantVista");
			return (Criteria) this;
		}

		public Criteria andBeforeDaysGrantVistaLessThan(Integer value) {
			addCriterion("before_Days_Grant_Vista <", value,
					"beforeDaysGrantVista");
			return (Criteria) this;
		}

		public Criteria andBeforeDaysGrantVistaLessThanOrEqualTo(Integer value) {
			addCriterion("before_Days_Grant_Vista <=", value,
					"beforeDaysGrantVista");
			return (Criteria) this;
		}

		public Criteria andBeforeDaysGrantVistaIn(List<Integer> values) {
			addCriterion("before_Days_Grant_Vista in", values,
					"beforeDaysGrantVista");
			return (Criteria) this;
		}

		public Criteria andBeforeDaysGrantVistaNotIn(List<Integer> values) {
			addCriterion("before_Days_Grant_Vista not in", values,
					"beforeDaysGrantVista");
			return (Criteria) this;
		}

		public Criteria andBeforeDaysGrantVistaBetween(Integer value1,
				Integer value2) {
			addCriterion("before_Days_Grant_Vista between", value1, value2,
					"beforeDaysGrantVista");
			return (Criteria) this;
		}

		public Criteria andBeforeDaysGrantVistaNotBetween(Integer value1,
				Integer value2) {
			addCriterion("before_Days_Grant_Vista not between", value1, value2,
					"beforeDaysGrantVista");
			return (Criteria) this;
		}

		public Criteria andDaysNightIsNull() {
			addCriterion("days_Night is null");
			return (Criteria) this;
		}

		public Criteria andDaysNightIsNotNull() {
			addCriterion("days_Night is not null");
			return (Criteria) this;
		}

		public Criteria andDaysNightEqualTo(Integer value) {
			addCriterion("days_Night =", value, "daysNight");
			return (Criteria) this;
		}

		public Criteria andDaysNightNotEqualTo(Integer value) {
			addCriterion("days_Night <>", value, "daysNight");
			return (Criteria) this;
		}

		public Criteria andDaysNightGreaterThan(Integer value) {
			addCriterion("days_Night >", value, "daysNight");
			return (Criteria) this;
		}

		public Criteria andDaysNightGreaterThanOrEqualTo(Integer value) {
			addCriterion("days_Night >=", value, "daysNight");
			return (Criteria) this;
		}

		public Criteria andDaysNightLessThan(Integer value) {
			addCriterion("days_Night <", value, "daysNight");
			return (Criteria) this;
		}

		public Criteria andDaysNightLessThanOrEqualTo(Integer value) {
			addCriterion("days_Night <=", value, "daysNight");
			return (Criteria) this;
		}

		public Criteria andDaysNightIn(List<Integer> values) {
			addCriterion("days_Night in", values, "daysNight");
			return (Criteria) this;
		}

		public Criteria andDaysNightNotIn(List<Integer> values) {
			addCriterion("days_Night not in", values, "daysNight");
			return (Criteria) this;
		}

		public Criteria andDaysNightBetween(Integer value1, Integer value2) {
			addCriterion("days_Night between", value1, value2, "daysNight");
			return (Criteria) this;
		}

		public Criteria andDaysNightNotBetween(Integer value1, Integer value2) {
			addCriterion("days_Night not between", value1, value2, "daysNight");
			return (Criteria) this;
		}

		public Criteria andDaysDuringIsNull() {
			addCriterion("days_During is null");
			return (Criteria) this;
		}

		public Criteria andDaysDuringIsNotNull() {
			addCriterion("days_During is not null");
			return (Criteria) this;
		}

		public Criteria andDaysDuringEqualTo(Integer value) {
			addCriterion("days_During =", value, "daysDuring");
			return (Criteria) this;
		}

		public Criteria andDaysDuringNotEqualTo(Integer value) {
			addCriterion("days_During <>", value, "daysDuring");
			return (Criteria) this;
		}

		public Criteria andDaysDuringGreaterThan(Integer value) {
			addCriterion("days_During >", value, "daysDuring");
			return (Criteria) this;
		}

		public Criteria andDaysDuringGreaterThanOrEqualTo(Integer value) {
			addCriterion("days_During >=", value, "daysDuring");
			return (Criteria) this;
		}

		public Criteria andDaysDuringLessThan(Integer value) {
			addCriterion("days_During <", value, "daysDuring");
			return (Criteria) this;
		}

		public Criteria andDaysDuringLessThanOrEqualTo(Integer value) {
			addCriterion("days_During <=", value, "daysDuring");
			return (Criteria) this;
		}

		public Criteria andDaysDuringIn(List<Integer> values) {
			addCriterion("days_During in", values, "daysDuring");
			return (Criteria) this;
		}

		public Criteria andDaysDuringNotIn(List<Integer> values) {
			addCriterion("days_During not in", values, "daysDuring");
			return (Criteria) this;
		}

		public Criteria andDaysDuringBetween(Integer value1, Integer value2) {
			addCriterion("days_During between", value1, value2, "daysDuring");
			return (Criteria) this;
		}

		public Criteria andDaysDuringNotBetween(Integer value1, Integer value2) {
			addCriterion("days_During not between", value1, value2,
					"daysDuring");
			return (Criteria) this;
		}

		public Criteria andLeaveCityIsNull() {
			addCriterion("leave_City is null");
			return (Criteria) this;
		}

		public Criteria andLeaveCityIsNotNull() {
			addCriterion("leave_City is not null");
			return (Criteria) this;
		}

		public Criteria andLeaveCityEqualTo(String value) {
			addCriterion("leave_City =", value, "leaveCity");
			return (Criteria) this;
		}

		public Criteria andLeaveCityNotEqualTo(String value) {
			addCriterion("leave_City <>", value, "leaveCity");
			return (Criteria) this;
		}

		public Criteria andLeaveCityGreaterThan(String value) {
			addCriterion("leave_City >", value, "leaveCity");
			return (Criteria) this;
		}

		public Criteria andLeaveCityGreaterThanOrEqualTo(String value) {
			addCriterion("leave_City >=", value, "leaveCity");
			return (Criteria) this;
		}

		public Criteria andLeaveCityLessThan(String value) {
			addCriterion("leave_City <", value, "leaveCity");
			return (Criteria) this;
		}

		public Criteria andLeaveCityLessThanOrEqualTo(String value) {
			addCriterion("leave_City <=", value, "leaveCity");
			return (Criteria) this;
		}

		public Criteria andLeaveCityLike(String value) {
			addCriterion("leave_City like", value, "leaveCity");
			return (Criteria) this;
		}

		public Criteria andLeaveCityNotLike(String value) {
			addCriterion("leave_City not like", value, "leaveCity");
			return (Criteria) this;
		}

		public Criteria andLeaveCityIn(List<String> values) {
			addCriterion("leave_City in", values, "leaveCity");
			return (Criteria) this;
		}

		public Criteria andLeaveCityNotIn(List<String> values) {
			addCriterion("leave_City not in", values, "leaveCity");
			return (Criteria) this;
		}

		public Criteria andLeaveCityBetween(String value1, String value2) {
			addCriterion("leave_City between", value1, value2, "leaveCity");
			return (Criteria) this;
		}

		public Criteria andLeaveCityNotBetween(String value1, String value2) {
			addCriterion("leave_City not between", value1, value2, "leaveCity");
			return (Criteria) this;
		}

		public Criteria andLeaveCityTrafficIsNull() {
			addCriterion("leave_City_Traffic is null");
			return (Criteria) this;
		}

		public Criteria andLeaveCityTrafficIsNotNull() {
			addCriterion("leave_City_Traffic is not null");
			return (Criteria) this;
		}

		public Criteria andLeaveCityTrafficEqualTo(String value) {
			addCriterion("leave_City_Traffic =", value, "leaveCityTraffic");
			return (Criteria) this;
		}

		public Criteria andLeaveCityTrafficNotEqualTo(String value) {
			addCriterion("leave_City_Traffic <>", value, "leaveCityTraffic");
			return (Criteria) this;
		}

		public Criteria andLeaveCityTrafficGreaterThan(String value) {
			addCriterion("leave_City_Traffic >", value, "leaveCityTraffic");
			return (Criteria) this;
		}

		public Criteria andLeaveCityTrafficGreaterThanOrEqualTo(String value) {
			addCriterion("leave_City_Traffic >=", value, "leaveCityTraffic");
			return (Criteria) this;
		}

		public Criteria andLeaveCityTrafficLessThan(String value) {
			addCriterion("leave_City_Traffic <", value, "leaveCityTraffic");
			return (Criteria) this;
		}

		public Criteria andLeaveCityTrafficLessThanOrEqualTo(String value) {
			addCriterion("leave_City_Traffic <=", value, "leaveCityTraffic");
			return (Criteria) this;
		}

		public Criteria andLeaveCityTrafficLike(String value) {
			addCriterion("leave_City_Traffic like", value, "leaveCityTraffic");
			return (Criteria) this;
		}

		public Criteria andLeaveCityTrafficNotLike(String value) {
			addCriterion("leave_City_Traffic not like", value,
					"leaveCityTraffic");
			return (Criteria) this;
		}

		public Criteria andLeaveCityTrafficIn(List<String> values) {
			addCriterion("leave_City_Traffic in", values, "leaveCityTraffic");
			return (Criteria) this;
		}

		public Criteria andLeaveCityTrafficNotIn(List<String> values) {
			addCriterion("leave_City_Traffic not in", values,
					"leaveCityTraffic");
			return (Criteria) this;
		}

		public Criteria andLeaveCityTrafficBetween(String value1, String value2) {
			addCriterion("leave_City_Traffic between", value1, value2,
					"leaveCityTraffic");
			return (Criteria) this;
		}

		public Criteria andLeaveCityTrafficNotBetween(String value1,
				String value2) {
			addCriterion("leave_City_Traffic not between", value1, value2,
					"leaveCityTraffic");
			return (Criteria) this;
		}

		public Criteria andReturnCityIsNull() {
			addCriterion("return_City is null");
			return (Criteria) this;
		}

		public Criteria andReturnCityIsNotNull() {
			addCriterion("return_City is not null");
			return (Criteria) this;
		}

		public Criteria andReturnCityEqualTo(String value) {
			addCriterion("return_City =", value, "returnCity");
			return (Criteria) this;
		}

		public Criteria andReturnCityNotEqualTo(String value) {
			addCriterion("return_City <>", value, "returnCity");
			return (Criteria) this;
		}

		public Criteria andReturnCityGreaterThan(String value) {
			addCriterion("return_City >", value, "returnCity");
			return (Criteria) this;
		}

		public Criteria andReturnCityGreaterThanOrEqualTo(String value) {
			addCriterion("return_City >=", value, "returnCity");
			return (Criteria) this;
		}

		public Criteria andReturnCityLessThan(String value) {
			addCriterion("return_City <", value, "returnCity");
			return (Criteria) this;
		}

		public Criteria andReturnCityLessThanOrEqualTo(String value) {
			addCriterion("return_City <=", value, "returnCity");
			return (Criteria) this;
		}

		public Criteria andReturnCityLike(String value) {
			addCriterion("return_City like", value, "returnCity");
			return (Criteria) this;
		}

		public Criteria andReturnCityNotLike(String value) {
			addCriterion("return_City not like", value, "returnCity");
			return (Criteria) this;
		}

		public Criteria andReturnCityIn(List<String> values) {
			addCriterion("return_City in", values, "returnCity");
			return (Criteria) this;
		}

		public Criteria andReturnCityNotIn(List<String> values) {
			addCriterion("return_City not in", values, "returnCity");
			return (Criteria) this;
		}

		public Criteria andReturnCityBetween(String value1, String value2) {
			addCriterion("return_City between", value1, value2, "returnCity");
			return (Criteria) this;
		}

		public Criteria andReturnCityNotBetween(String value1, String value2) {
			addCriterion("return_City not between", value1, value2,
					"returnCity");
			return (Criteria) this;
		}

		public Criteria andReturnCityTrafficIsNull() {
			addCriterion("return_City_Traffic is null");
			return (Criteria) this;
		}

		public Criteria andReturnCityTrafficIsNotNull() {
			addCriterion("return_City_Traffic is not null");
			return (Criteria) this;
		}

		public Criteria andReturnCityTrafficEqualTo(String value) {
			addCriterion("return_City_Traffic =", value, "returnCityTraffic");
			return (Criteria) this;
		}

		public Criteria andReturnCityTrafficNotEqualTo(String value) {
			addCriterion("return_City_Traffic <>", value, "returnCityTraffic");
			return (Criteria) this;
		}

		public Criteria andReturnCityTrafficGreaterThan(String value) {
			addCriterion("return_City_Traffic >", value, "returnCityTraffic");
			return (Criteria) this;
		}

		public Criteria andReturnCityTrafficGreaterThanOrEqualTo(String value) {
			addCriterion("return_City_Traffic >=", value, "returnCityTraffic");
			return (Criteria) this;
		}

		public Criteria andReturnCityTrafficLessThan(String value) {
			addCriterion("return_City_Traffic <", value, "returnCityTraffic");
			return (Criteria) this;
		}

		public Criteria andReturnCityTrafficLessThanOrEqualTo(String value) {
			addCriterion("return_City_Traffic <=", value, "returnCityTraffic");
			return (Criteria) this;
		}

		public Criteria andReturnCityTrafficLike(String value) {
			addCriterion("return_City_Traffic like", value, "returnCityTraffic");
			return (Criteria) this;
		}

		public Criteria andReturnCityTrafficNotLike(String value) {
			addCriterion("return_City_Traffic not like", value,
					"returnCityTraffic");
			return (Criteria) this;
		}

		public Criteria andReturnCityTrafficIn(List<String> values) {
			addCriterion("return_City_Traffic in", values, "returnCityTraffic");
			return (Criteria) this;
		}

		public Criteria andReturnCityTrafficNotIn(List<String> values) {
			addCriterion("return_City_Traffic not in", values,
					"returnCityTraffic");
			return (Criteria) this;
		}

		public Criteria andReturnCityTrafficBetween(String value1, String value2) {
			addCriterion("return_City_Traffic between", value1, value2,
					"returnCityTraffic");
			return (Criteria) this;
		}

		public Criteria andReturnCityTrafficNotBetween(String value1,
				String value2) {
			addCriterion("return_City_Traffic not between", value1, value2,
					"returnCityTraffic");
			return (Criteria) this;
		}

		public Criteria andThroughCitysIsNull() {
			addCriterion("through_Citys is null");
			return (Criteria) this;
		}

		public Criteria andThroughCitysIsNotNull() {
			addCriterion("through_Citys is not null");
			return (Criteria) this;
		}

		public Criteria andThroughCitysEqualTo(String value) {
			addCriterion("through_Citys =", value, "throughCitys");
			return (Criteria) this;
		}

		public Criteria andThroughCitysNotEqualTo(String value) {
			addCriterion("through_Citys <>", value, "throughCitys");
			return (Criteria) this;
		}

		public Criteria andThroughCitysGreaterThan(String value) {
			addCriterion("through_Citys >", value, "throughCitys");
			return (Criteria) this;
		}

		public Criteria andThroughCitysGreaterThanOrEqualTo(String value) {
			addCriterion("through_Citys >=", value, "throughCitys");
			return (Criteria) this;
		}

		public Criteria andThroughCitysLessThan(String value) {
			addCriterion("through_Citys <", value, "throughCitys");
			return (Criteria) this;
		}

		public Criteria andThroughCitysLessThanOrEqualTo(String value) {
			addCriterion("through_Citys <=", value, "throughCitys");
			return (Criteria) this;
		}

		public Criteria andThroughCitysLike(String value) {
			addCriterion("through_Citys like", value, "throughCitys");
			return (Criteria) this;
		}

		public Criteria andThroughCitysNotLike(String value) {
			addCriterion("through_Citys not like", value, "throughCitys");
			return (Criteria) this;
		}

		public Criteria andThroughCitysIn(List<String> values) {
			addCriterion("through_Citys in", values, "throughCitys");
			return (Criteria) this;
		}

		public Criteria andThroughCitysNotIn(List<String> values) {
			addCriterion("through_Citys not in", values, "throughCitys");
			return (Criteria) this;
		}

		public Criteria andThroughCitysBetween(String value1, String value2) {
			addCriterion("through_Citys between", value1, value2,
					"throughCitys");
			return (Criteria) this;
		}

		public Criteria andThroughCitysNotBetween(String value1, String value2) {
			addCriterion("through_Citys not between", value1, value2,
					"throughCitys");
			return (Criteria) this;
		}

		public Criteria andTourAttractionsIsNull() {
			addCriterion("tour_Attractions is null");
			return (Criteria) this;
		}

		public Criteria andTourAttractionsIsNotNull() {
			addCriterion("tour_Attractions is not null");
			return (Criteria) this;
		}

		public Criteria andTourAttractionsEqualTo(String value) {
			addCriterion("tour_Attractions =", value, "tourAttractions");
			return (Criteria) this;
		}

		public Criteria andTourAttractionsNotEqualTo(String value) {
			addCriterion("tour_Attractions <>", value, "tourAttractions");
			return (Criteria) this;
		}

		public Criteria andTourAttractionsGreaterThan(String value) {
			addCriterion("tour_Attractions >", value, "tourAttractions");
			return (Criteria) this;
		}

		public Criteria andTourAttractionsGreaterThanOrEqualTo(String value) {
			addCriterion("tour_Attractions >=", value, "tourAttractions");
			return (Criteria) this;
		}

		public Criteria andTourAttractionsLessThan(String value) {
			addCriterion("tour_Attractions <", value, "tourAttractions");
			return (Criteria) this;
		}

		public Criteria andTourAttractionsLessThanOrEqualTo(String value) {
			addCriterion("tour_Attractions <=", value, "tourAttractions");
			return (Criteria) this;
		}

		public Criteria andTourAttractionsLike(String value) {
			addCriterion("tour_Attractions like", value, "tourAttractions");
			return (Criteria) this;
		}

		public Criteria andTourAttractionsNotLike(String value) {
			addCriterion("tour_Attractions not like", value, "tourAttractions");
			return (Criteria) this;
		}

		public Criteria andTourAttractionsIn(List<String> values) {
			addCriterion("tour_Attractions in", values, "tourAttractions");
			return (Criteria) this;
		}

		public Criteria andTourAttractionsNotIn(List<String> values) {
			addCriterion("tour_Attractions not in", values, "tourAttractions");
			return (Criteria) this;
		}

		public Criteria andTourAttractionsBetween(String value1, String value2) {
			addCriterion("tour_Attractions between", value1, value2,
					"tourAttractions");
			return (Criteria) this;
		}

		public Criteria andTourAttractionsNotBetween(String value1,
				String value2) {
			addCriterion("tour_Attractions not between", value1, value2,
					"tourAttractions");
			return (Criteria) this;
		}

		public Criteria andKeyWordsIsNull() {
			addCriterion("key_Words is null");
			return (Criteria) this;
		}

		public Criteria andKeyWordsIsNotNull() {
			addCriterion("key_Words is not null");
			return (Criteria) this;
		}

		public Criteria andKeyWordsEqualTo(String value) {
			addCriterion("key_Words =", value, "keyWords");
			return (Criteria) this;
		}

		public Criteria andKeyWordsNotEqualTo(String value) {
			addCriterion("key_Words <>", value, "keyWords");
			return (Criteria) this;
		}

		public Criteria andKeyWordsGreaterThan(String value) {
			addCriterion("key_Words >", value, "keyWords");
			return (Criteria) this;
		}

		public Criteria andKeyWordsGreaterThanOrEqualTo(String value) {
			addCriterion("key_Words >=", value, "keyWords");
			return (Criteria) this;
		}

		public Criteria andKeyWordsLessThan(String value) {
			addCriterion("key_Words <", value, "keyWords");
			return (Criteria) this;
		}

		public Criteria andKeyWordsLessThanOrEqualTo(String value) {
			addCriterion("key_Words <=", value, "keyWords");
			return (Criteria) this;
		}

		public Criteria andKeyWordsLike(String value) {
			addCriterion("key_Words like", value, "keyWords");
			return (Criteria) this;
		}

		public Criteria andKeyWordsNotLike(String value) {
			addCriterion("key_Words not like", value, "keyWords");
			return (Criteria) this;
		}

		public Criteria andKeyWordsIn(List<String> values) {
			addCriterion("key_Words in", values, "keyWords");
			return (Criteria) this;
		}

		public Criteria andKeyWordsNotIn(List<String> values) {
			addCriterion("key_Words not in", values, "keyWords");
			return (Criteria) this;
		}

		public Criteria andKeyWordsBetween(String value1, String value2) {
			addCriterion("key_Words between", value1, value2, "keyWords");
			return (Criteria) this;
		}

		public Criteria andKeyWordsNotBetween(String value1, String value2) {
			addCriterion("key_Words not between", value1, value2, "keyWords");
			return (Criteria) this;
		}

		public Criteria andDesignStatusIsNull() {
			addCriterion("design_Status is null");
			return (Criteria) this;
		}

		public Criteria andDesignStatusIsNotNull() {
			addCriterion("design_Status is not null");
			return (Criteria) this;
		}

		public Criteria andDesignStatusEqualTo(String value) {
			addCriterion("design_Status =", value, "designStatus");
			return (Criteria) this;
		}

		public Criteria andDesignStatusNotEqualTo(String value) {
			addCriterion("design_Status <>", value, "designStatus");
			return (Criteria) this;
		}

		public Criteria andDesignStatusGreaterThan(String value) {
			addCriterion("design_Status >", value, "designStatus");
			return (Criteria) this;
		}

		public Criteria andDesignStatusGreaterThanOrEqualTo(String value) {
			addCriterion("design_Status >=", value, "designStatus");
			return (Criteria) this;
		}

		public Criteria andDesignStatusLessThan(String value) {
			addCriterion("design_Status <", value, "designStatus");
			return (Criteria) this;
		}

		public Criteria andDesignStatusLessThanOrEqualTo(String value) {
			addCriterion("design_Status <=", value, "designStatus");
			return (Criteria) this;
		}

		public Criteria andDesignStatusLike(String value) {
			addCriterion("design_Status like", value, "designStatus");
			return (Criteria) this;
		}

		public Criteria andDesignStatusNotLike(String value) {
			addCriterion("design_Status not like", value, "designStatus");
			return (Criteria) this;
		}

		public Criteria andDesignStatusIn(List<String> values) {
			addCriterion("design_Status in", values, "designStatus");
			return (Criteria) this;
		}

		public Criteria andDesignStatusNotIn(List<String> values) {
			addCriterion("design_Status not in", values, "designStatus");
			return (Criteria) this;
		}

		public Criteria andDesignStatusBetween(String value1, String value2) {
			addCriterion("design_Status between", value1, value2,
					"designStatus");
			return (Criteria) this;
		}

		public Criteria andDesignStatusNotBetween(String value1, String value2) {
			addCriterion("design_Status not between", value1, value2,
					"designStatus");
			return (Criteria) this;
		}

		public Criteria andGmtDesingCompleteIsNull() {
			addCriterion("gmt_Desing_Complete is null");
			return (Criteria) this;
		}

		public Criteria andGmtDesingCompleteIsNotNull() {
			addCriterion("gmt_Desing_Complete is not null");
			return (Criteria) this;
		}

		public Criteria andGmtDesingCompleteEqualTo(Date value) {
			addCriterion("gmt_Desing_Complete =", value, "gmtDesingComplete");
			return (Criteria) this;
		}

		public Criteria andGmtDesingCompleteNotEqualTo(Date value) {
			addCriterion("gmt_Desing_Complete <>", value, "gmtDesingComplete");
			return (Criteria) this;
		}

		public Criteria andGmtDesingCompleteGreaterThan(Date value) {
			addCriterion("gmt_Desing_Complete >", value, "gmtDesingComplete");
			return (Criteria) this;
		}

		public Criteria andGmtDesingCompleteGreaterThanOrEqualTo(Date value) {
			addCriterion("gmt_Desing_Complete >=", value, "gmtDesingComplete");
			return (Criteria) this;
		}

		public Criteria andGmtDesingCompleteLessThan(Date value) {
			addCriterion("gmt_Desing_Complete <", value, "gmtDesingComplete");
			return (Criteria) this;
		}

		public Criteria andGmtDesingCompleteLessThanOrEqualTo(Date value) {
			addCriterion("gmt_Desing_Complete <=", value, "gmtDesingComplete");
			return (Criteria) this;
		}

		public Criteria andGmtDesingCompleteIn(List<Date> values) {
			addCriterion("gmt_Desing_Complete in", values, "gmtDesingComplete");
			return (Criteria) this;
		}

		public Criteria andGmtDesingCompleteNotIn(List<Date> values) {
			addCriterion("gmt_Desing_Complete not in", values,
					"gmtDesingComplete");
			return (Criteria) this;
		}

		public Criteria andGmtDesingCompleteBetween(Date value1, Date value2) {
			addCriterion("gmt_Desing_Complete between", value1, value2,
					"gmtDesingComplete");
			return (Criteria) this;
		}

		public Criteria andGmtDesingCompleteNotBetween(Date value1, Date value2) {
			addCriterion("gmt_Desing_Complete not between", value1, value2,
					"gmtDesingComplete");
			return (Criteria) this;
		}

		public Criteria andIsEnableIsNull() {
			addCriterion("is_Enable is null");
			return (Criteria) this;
		}

		public Criteria andIsEnableIsNotNull() {
			addCriterion("is_Enable is not null");
			return (Criteria) this;
		}

		public Criteria andIsEnableEqualTo(Short value) {
			addCriterion("is_Enable =", value, "isEnable");
			return (Criteria) this;
		}

		public Criteria andIsEnableNotEqualTo(Short value) {
			addCriterion("is_Enable <>", value, "isEnable");
			return (Criteria) this;
		}

		public Criteria andIsEnableGreaterThan(Short value) {
			addCriterion("is_Enable >", value, "isEnable");
			return (Criteria) this;
		}

		public Criteria andIsEnableGreaterThanOrEqualTo(Short value) {
			addCriterion("is_Enable >=", value, "isEnable");
			return (Criteria) this;
		}

		public Criteria andIsEnableLessThan(Short value) {
			addCriterion("is_Enable <", value, "isEnable");
			return (Criteria) this;
		}

		public Criteria andIsEnableLessThanOrEqualTo(Short value) {
			addCriterion("is_Enable <=", value, "isEnable");
			return (Criteria) this;
		}

		public Criteria andIsEnableIn(List<Short> values) {
			addCriterion("is_Enable in", values, "isEnable");
			return (Criteria) this;
		}

		public Criteria andIsEnableNotIn(List<Short> values) {
			addCriterion("is_Enable not in", values, "isEnable");
			return (Criteria) this;
		}

		public Criteria andIsEnableBetween(Short value1, Short value2) {
			addCriterion("is_Enable between", value1, value2, "isEnable");
			return (Criteria) this;
		}

		public Criteria andIsEnableNotBetween(Short value1, Short value2) {
			addCriterion("is_Enable not between", value1, value2, "isEnable");
			return (Criteria) this;
		}

		public Criteria andGmtCreateIsNull() {
			addCriterion("gmt_Create is null");
			return (Criteria) this;
		}

		public Criteria andGmtCreateIsNotNull() {
			addCriterion("gmt_Create is not null");
			return (Criteria) this;
		}

		public Criteria andGmtCreateEqualTo(Date value) {
			addCriterion("gmt_Create =", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateNotEqualTo(Date value) {
			addCriterion("gmt_Create <>", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateGreaterThan(Date value) {
			addCriterion("gmt_Create >", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
			addCriterion("gmt_Create >=", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateLessThan(Date value) {
			addCriterion("gmt_Create <", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
			addCriterion("gmt_Create <=", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateIn(List<Date> values) {
			addCriterion("gmt_Create in", values, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateNotIn(List<Date> values) {
			addCriterion("gmt_Create not in", values, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateBetween(Date value1, Date value2) {
			addCriterion("gmt_Create between", value1, value2, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
			addCriterion("gmt_Create not between", value1, value2, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andCreatorIsNull() {
			addCriterion("creator is null");
			return (Criteria) this;
		}

		public Criteria andCreatorIsNotNull() {
			addCriterion("creator is not null");
			return (Criteria) this;
		}

		public Criteria andCreatorEqualTo(String value) {
			addCriterion("creator =", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotEqualTo(String value) {
			addCriterion("creator <>", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorGreaterThan(String value) {
			addCriterion("creator >", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorGreaterThanOrEqualTo(String value) {
			addCriterion("creator >=", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLessThan(String value) {
			addCriterion("creator <", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLessThanOrEqualTo(String value) {
			addCriterion("creator <=", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLike(String value) {
			addCriterion("creator like", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotLike(String value) {
			addCriterion("creator not like", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorIn(List<String> values) {
			addCriterion("creator in", values, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotIn(List<String> values) {
			addCriterion("creator not in", values, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorBetween(String value1, String value2) {
			addCriterion("creator between", value1, value2, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotBetween(String value1, String value2) {
			addCriterion("creator not between", value1, value2, "creator");
			return (Criteria) this;
		}

		public Criteria andGmtModifyIsNull() {
			addCriterion("gmt_Modify is null");
			return (Criteria) this;
		}

		public Criteria andGmtModifyIsNotNull() {
			addCriterion("gmt_Modify is not null");
			return (Criteria) this;
		}

		public Criteria andGmtModifyEqualTo(Date value) {
			addCriterion("gmt_Modify =", value, "gmtModify");
			return (Criteria) this;
		}

		public Criteria andGmtModifyNotEqualTo(Date value) {
			addCriterion("gmt_Modify <>", value, "gmtModify");
			return (Criteria) this;
		}

		public Criteria andGmtModifyGreaterThan(Date value) {
			addCriterion("gmt_Modify >", value, "gmtModify");
			return (Criteria) this;
		}

		public Criteria andGmtModifyGreaterThanOrEqualTo(Date value) {
			addCriterion("gmt_Modify >=", value, "gmtModify");
			return (Criteria) this;
		}

		public Criteria andGmtModifyLessThan(Date value) {
			addCriterion("gmt_Modify <", value, "gmtModify");
			return (Criteria) this;
		}

		public Criteria andGmtModifyLessThanOrEqualTo(Date value) {
			addCriterion("gmt_Modify <=", value, "gmtModify");
			return (Criteria) this;
		}

		public Criteria andGmtModifyIn(List<Date> values) {
			addCriterion("gmt_Modify in", values, "gmtModify");
			return (Criteria) this;
		}

		public Criteria andGmtModifyNotIn(List<Date> values) {
			addCriterion("gmt_Modify not in", values, "gmtModify");
			return (Criteria) this;
		}

		public Criteria andGmtModifyBetween(Date value1, Date value2) {
			addCriterion("gmt_Modify between", value1, value2, "gmtModify");
			return (Criteria) this;
		}

		public Criteria andGmtModifyNotBetween(Date value1, Date value2) {
			addCriterion("gmt_Modify not between", value1, value2, "gmtModify");
			return (Criteria) this;
		}

		public Criteria andModifierIsNull() {
			addCriterion("modifier is null");
			return (Criteria) this;
		}

		public Criteria andModifierIsNotNull() {
			addCriterion("modifier is not null");
			return (Criteria) this;
		}

		public Criteria andModifierEqualTo(String value) {
			addCriterion("modifier =", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotEqualTo(String value) {
			addCriterion("modifier <>", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierGreaterThan(String value) {
			addCriterion("modifier >", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierGreaterThanOrEqualTo(String value) {
			addCriterion("modifier >=", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierLessThan(String value) {
			addCriterion("modifier <", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierLessThanOrEqualTo(String value) {
			addCriterion("modifier <=", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierLike(String value) {
			addCriterion("modifier like", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotLike(String value) {
			addCriterion("modifier not like", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierIn(List<String> values) {
			addCriterion("modifier in", values, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotIn(List<String> values) {
			addCriterion("modifier not in", values, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierBetween(String value1, String value2) {
			addCriterion("modifier between", value1, value2, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotBetween(String value1, String value2) {
			addCriterion("modifier not between", value1, value2, "modifier");
			return (Criteria) this;
		}

		public Criteria andMemoIsNull() {
			addCriterion("memo is null");
			return (Criteria) this;
		}

		public Criteria andMemoIsNotNull() {
			addCriterion("memo is not null");
			return (Criteria) this;
		}

		public Criteria andMemoEqualTo(String value) {
			addCriterion("memo =", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotEqualTo(String value) {
			addCriterion("memo <>", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoGreaterThan(String value) {
			addCriterion("memo >", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoGreaterThanOrEqualTo(String value) {
			addCriterion("memo >=", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoLessThan(String value) {
			addCriterion("memo <", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoLessThanOrEqualTo(String value) {
			addCriterion("memo <=", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoLike(String value) {
			addCriterion("memo like", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotLike(String value) {
			addCriterion("memo not like", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoIn(List<String> values) {
			addCriterion("memo in", values, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotIn(List<String> values) {
			addCriterion("memo not in", values, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoBetween(String value1, String value2) {
			addCriterion("memo between", value1, value2, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotBetween(String value1, String value2) {
			addCriterion("memo not between", value1, value2, "memo");
			return (Criteria) this;
		}

		public Criteria andAuditOpinionIsNull() {
			addCriterion("audit_Opinion is null");
			return (Criteria) this;
		}

		public Criteria andAuditOpinionIsNotNull() {
			addCriterion("audit_Opinion is not null");
			return (Criteria) this;
		}

		public Criteria andAuditOpinionEqualTo(String value) {
			addCriterion("audit_Opinion =", value, "auditOpinion");
			return (Criteria) this;
		}

		public Criteria andAuditOpinionNotEqualTo(String value) {
			addCriterion("audit_Opinion <>", value, "auditOpinion");
			return (Criteria) this;
		}

		public Criteria andAuditOpinionGreaterThan(String value) {
			addCriterion("audit_Opinion >", value, "auditOpinion");
			return (Criteria) this;
		}

		public Criteria andAuditOpinionGreaterThanOrEqualTo(String value) {
			addCriterion("audit_Opinion >=", value, "auditOpinion");
			return (Criteria) this;
		}

		public Criteria andAuditOpinionLessThan(String value) {
			addCriterion("audit_Opinion <", value, "auditOpinion");
			return (Criteria) this;
		}

		public Criteria andAuditOpinionLessThanOrEqualTo(String value) {
			addCriterion("audit_Opinion <=", value, "auditOpinion");
			return (Criteria) this;
		}

		public Criteria andAuditOpinionLike(String value) {
			addCriterion("audit_Opinion like", value, "auditOpinion");
			return (Criteria) this;
		}

		public Criteria andAuditOpinionNotLike(String value) {
			addCriterion("audit_Opinion not like", value, "auditOpinion");
			return (Criteria) this;
		}

		public Criteria andAuditOpinionIn(List<String> values) {
			addCriterion("audit_Opinion in", values, "auditOpinion");
			return (Criteria) this;
		}

		public Criteria andAuditOpinionNotIn(List<String> values) {
			addCriterion("audit_Opinion not in", values, "auditOpinion");
			return (Criteria) this;
		}

		public Criteria andAuditOpinionBetween(String value1, String value2) {
			addCriterion("audit_Opinion between", value1, value2,
					"auditOpinion");
			return (Criteria) this;
		}

		public Criteria andAuditOpinionNotBetween(String value1, String value2) {
			addCriterion("audit_Opinion not between", value1, value2,
					"auditOpinion");
			return (Criteria) this;
		}

		public Criteria andAuditStatusIsNull() {
			addCriterion("audit_Status is null");
			return (Criteria) this;
		}

		public Criteria andAuditStatusIsNotNull() {
			addCriterion("audit_Status is not null");
			return (Criteria) this;
		}

		public Criteria andAuditStatusEqualTo(String value) {
			addCriterion("audit_Status =", value, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusNotEqualTo(String value) {
			addCriterion("audit_Status <>", value, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusGreaterThan(String value) {
			addCriterion("audit_Status >", value, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusGreaterThanOrEqualTo(String value) {
			addCriterion("audit_Status >=", value, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusLessThan(String value) {
			addCriterion("audit_Status <", value, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusLessThanOrEqualTo(String value) {
			addCriterion("audit_Status <=", value, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusLike(String value) {
			addCriterion("audit_Status like", value, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusNotLike(String value) {
			addCriterion("audit_Status not like", value, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusIn(List<String> values) {
			addCriterion("audit_Status in", values, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusNotIn(List<String> values) {
			addCriterion("audit_Status not in", values, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusBetween(String value1, String value2) {
			addCriterion("audit_Status between", value1, value2, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusNotBetween(String value1, String value2) {
			addCriterion("audit_Status not between", value1, value2,
					"auditStatus");
			return (Criteria) this;
		}

		public Criteria andTargetCustomersIsNull() {
			addCriterion("target_Customers is null");
			return (Criteria) this;
		}

		public Criteria andTargetCustomersIsNotNull() {
			addCriterion("target_Customers is not null");
			return (Criteria) this;
		}

		public Criteria andTargetCustomersEqualTo(String value) {
			addCriterion("target_Customers =", value, "targetCustomers");
			return (Criteria) this;
		}

		public Criteria andTargetCustomersNotEqualTo(String value) {
			addCriterion("target_Customers <>", value, "targetCustomers");
			return (Criteria) this;
		}

		public Criteria andTargetCustomersGreaterThan(String value) {
			addCriterion("target_Customers >", value, "targetCustomers");
			return (Criteria) this;
		}

		public Criteria andTargetCustomersGreaterThanOrEqualTo(String value) {
			addCriterion("target_Customers >=", value, "targetCustomers");
			return (Criteria) this;
		}

		public Criteria andTargetCustomersLessThan(String value) {
			addCriterion("target_Customers <", value, "targetCustomers");
			return (Criteria) this;
		}

		public Criteria andTargetCustomersLessThanOrEqualTo(String value) {
			addCriterion("target_Customers <=", value, "targetCustomers");
			return (Criteria) this;
		}

		public Criteria andTargetCustomersLike(String value) {
			addCriterion("target_Customers like", value, "targetCustomers");
			return (Criteria) this;
		}

		public Criteria andTargetCustomersNotLike(String value) {
			addCriterion("target_Customers not like", value, "targetCustomers");
			return (Criteria) this;
		}

		public Criteria andTargetCustomersIn(List<String> values) {
			addCriterion("target_Customers in", values, "targetCustomers");
			return (Criteria) this;
		}

		public Criteria andTargetCustomersNotIn(List<String> values) {
			addCriterion("target_Customers not in", values, "targetCustomers");
			return (Criteria) this;
		}

		public Criteria andTargetCustomersBetween(String value1, String value2) {
			addCriterion("target_Customers between", value1, value2,
					"targetCustomers");
			return (Criteria) this;
		}

		public Criteria andTargetCustomersNotBetween(String value1,
				String value2) {
			addCriterion("target_Customers not between", value1, value2,
					"targetCustomers");
			return (Criteria) this;
		}

		public Criteria andTourPurposeIsNull() {
			addCriterion("tour_Purpose is null");
			return (Criteria) this;
		}

		public Criteria andTourPurposeIsNotNull() {
			addCriterion("tour_Purpose is not null");
			return (Criteria) this;
		}

		public Criteria andTourPurposeEqualTo(String value) {
			addCriterion("tour_Purpose =", value, "tourPurpose");
			return (Criteria) this;
		}

		public Criteria andTourPurposeNotEqualTo(String value) {
			addCriterion("tour_Purpose <>", value, "tourPurpose");
			return (Criteria) this;
		}

		public Criteria andTourPurposeGreaterThan(String value) {
			addCriterion("tour_Purpose >", value, "tourPurpose");
			return (Criteria) this;
		}

		public Criteria andTourPurposeGreaterThanOrEqualTo(String value) {
			addCriterion("tour_Purpose >=", value, "tourPurpose");
			return (Criteria) this;
		}

		public Criteria andTourPurposeLessThan(String value) {
			addCriterion("tour_Purpose <", value, "tourPurpose");
			return (Criteria) this;
		}

		public Criteria andTourPurposeLessThanOrEqualTo(String value) {
			addCriterion("tour_Purpose <=", value, "tourPurpose");
			return (Criteria) this;
		}

		public Criteria andTourPurposeLike(String value) {
			addCriterion("tour_Purpose like", value, "tourPurpose");
			return (Criteria) this;
		}

		public Criteria andTourPurposeNotLike(String value) {
			addCriterion("tour_Purpose not like", value, "tourPurpose");
			return (Criteria) this;
		}

		public Criteria andTourPurposeIn(List<String> values) {
			addCriterion("tour_Purpose in", values, "tourPurpose");
			return (Criteria) this;
		}

		public Criteria andTourPurposeNotIn(List<String> values) {
			addCriterion("tour_Purpose not in", values, "tourPurpose");
			return (Criteria) this;
		}

		public Criteria andTourPurposeBetween(String value1, String value2) {
			addCriterion("tour_Purpose between", value1, value2, "tourPurpose");
			return (Criteria) this;
		}

		public Criteria andTourPurposeNotBetween(String value1, String value2) {
			addCriterion("tour_Purpose not between", value1, value2,
					"tourPurpose");
			return (Criteria) this;
		}

		public Criteria andIsDeletedIsNull() {
			addCriterion("is_Deleted is null");
			return (Criteria) this;
		}

		public Criteria andIsDeletedIsNotNull() {
			addCriterion("is_Deleted is not null");
			return (Criteria) this;
		}

		public Criteria andIsDeletedEqualTo(Short value) {
			addCriterion("is_Deleted =", value, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedNotEqualTo(Short value) {
			addCriterion("is_Deleted <>", value, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedGreaterThan(Short value) {
			addCriterion("is_Deleted >", value, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedGreaterThanOrEqualTo(Short value) {
			addCriterion("is_Deleted >=", value, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedLessThan(Short value) {
			addCriterion("is_Deleted <", value, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedLessThanOrEqualTo(Short value) {
			addCriterion("is_Deleted <=", value, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedIn(List<Short> values) {
			addCriterion("is_Deleted in", values, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedNotIn(List<Short> values) {
			addCriterion("is_Deleted not in", values, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedBetween(Short value1, Short value2) {
			addCriterion("is_Deleted between", value1, value2, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedNotBetween(Short value1, Short value2) {
			addCriterion("is_Deleted not between", value1, value2, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andPvIsNull() {
			addCriterion("PV is null");
			return (Criteria) this;
		}

		public Criteria andPvIsNotNull() {
			addCriterion("PV is not null");
			return (Criteria) this;
		}

		public Criteria andPvEqualTo(Long value) {
			addCriterion("PV =", value, "pv");
			return (Criteria) this;
		}

		public Criteria andPvNotEqualTo(Long value) {
			addCriterion("PV <>", value, "pv");
			return (Criteria) this;
		}

		public Criteria andPvGreaterThan(Long value) {
			addCriterion("PV >", value, "pv");
			return (Criteria) this;
		}

		public Criteria andPvGreaterThanOrEqualTo(Long value) {
			addCriterion("PV >=", value, "pv");
			return (Criteria) this;
		}

		public Criteria andPvLessThan(Long value) {
			addCriterion("PV <", value, "pv");
			return (Criteria) this;
		}

		public Criteria andPvLessThanOrEqualTo(Long value) {
			addCriterion("PV <=", value, "pv");
			return (Criteria) this;
		}

		public Criteria andPvIn(List<Long> values) {
			addCriterion("PV in", values, "pv");
			return (Criteria) this;
		}

		public Criteria andPvNotIn(List<Long> values) {
			addCriterion("PV not in", values, "pv");
			return (Criteria) this;
		}

		public Criteria andPvBetween(Long value1, Long value2) {
			addCriterion("PV between", value1, value2, "pv");
			return (Criteria) this;
		}

		public Criteria andPvNotBetween(Long value1, Long value2) {
			addCriterion("PV not between", value1, value2, "pv");
			return (Criteria) this;
		}

		public Criteria andApplicableTypeIsNull() {
			addCriterion("applicable_Type is null");
			return (Criteria) this;
		}

		public Criteria andApplicableTypeIsNotNull() {
			addCriterion("applicable_Type is not null");
			return (Criteria) this;
		}

		public Criteria andApplicableTypeEqualTo(String value) {
			addCriterion("applicable_Type =", value, "applicableType");
			return (Criteria) this;
		}

		public Criteria andApplicableTypeNotEqualTo(String value) {
			addCriterion("applicable_Type <>", value, "applicableType");
			return (Criteria) this;
		}

		public Criteria andApplicableTypeGreaterThan(String value) {
			addCriterion("applicable_Type >", value, "applicableType");
			return (Criteria) this;
		}

		public Criteria andApplicableTypeGreaterThanOrEqualTo(String value) {
			addCriterion("applicable_Type >=", value, "applicableType");
			return (Criteria) this;
		}

		public Criteria andApplicableTypeLessThan(String value) {
			addCriterion("applicable_Type <", value, "applicableType");
			return (Criteria) this;
		}

		public Criteria andApplicableTypeLessThanOrEqualTo(String value) {
			addCriterion("applicable_Type <=", value, "applicableType");
			return (Criteria) this;
		}

		public Criteria andApplicableTypeLike(String value) {
			addCriterion("applicable_Type like", value, "applicableType");
			return (Criteria) this;
		}

		public Criteria andApplicableTypeNotLike(String value) {
			addCriterion("applicable_Type not like", value, "applicableType");
			return (Criteria) this;
		}

		public Criteria andApplicableTypeIn(List<String> values) {
			addCriterion("applicable_Type in", values, "applicableType");
			return (Criteria) this;
		}

		public Criteria andApplicableTypeNotIn(List<String> values) {
			addCriterion("applicable_Type not in", values, "applicableType");
			return (Criteria) this;
		}

		public Criteria andApplicableTypeBetween(String value1, String value2) {
			addCriterion("applicable_Type between", value1, value2,
					"applicableType");
			return (Criteria) this;
		}

		public Criteria andApplicableTypeNotBetween(String value1, String value2) {
			addCriterion("applicable_Type not between", value1, value2,
					"applicableType");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tour_line
	 * @mbggenerated  Tue Jun 18 19:51:47 CST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tour_line
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 18 19:00:38 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}